export type DrillQuestion = {
  id: string;
  level: 'A0' | 'A1' | 'A2' | 'B1';
  lessonId: string;
  prompt: string;
  answer: string;
  tags: string[];
};

/** Seed pool for daily drill (Phase 0). Expand as levels are piloted. */
export const DRILL_QUESTIONS: DrillQuestion[] = [
  {
    id: 'a0-01-mc-greeting',
    level: 'A0',
    lessonId: 'a0/01-greetings-and-introductions',
    prompt: "It is 20:00. You arrive at a neighbour's house. What do you say?",
    answer: 'Goedenavond (not welterusten unless they go to bed)',
    tags: ['greetings', 'multiple-choice'],
  },
  {
    id: 'a0-01-name-question',
    level: 'A0',
    lessonId: 'a0/01-greetings-and-introductions',
    prompt: 'Translate: What is your name?',
    answer: 'Hoe heet je? (or Hoe heet jij?)',
    tags: ['questions', 'translation'],
  },
  {
    id: 'a0-01-ben-jij',
    level: 'A0',
    lessonId: 'a0/01-greetings-and-introductions',
    prompt: 'Fix: Bent jij Tom?',
    answer: 'Ben jij Tom? (t drops before jij in questions)',
    tags: ['word-order', 'questions'],
  },
  {
    id: 'a0-02-spell',
    level: 'A0',
    lessonId: 'a0/02-alphabet-and-spelling',
    prompt: 'Translate: How do you spell that?',
    answer: 'Hoe spel je dat?',
    tags: ['spelling', 'translation'],
  },
  {
    id: 'a0-03-age',
    level: 'A0',
    lessonId: 'a0/03-numbers-0-20-and-age',
    prompt: 'I am twenty years old.',
    answer: 'Ik ben twintig jaar.',
    tags: ['numbers', 'zijn', 'translation'],
  },
  {
    id: 'a0-04-u-formal',
    level: 'A0',
    lessonId: 'a0/04-pronouns-and-zijn',
    prompt: 'You speak to an official. Fill in: ___ bent u?',
    answer: 'Hoe (Hoe bent u? = How are you?, formal)',
    tags: ['pronouns', 'formal'],
  },
  {
    id: 'a0-05-honger',
    level: 'A0',
    lessonId: 'a0/05-hebben-and-everyday-things',
    prompt: 'Fix: Ik ben honger.',
    answer: 'Ik heb honger.',
    tags: ['hebben', 'common-mistake'],
  },
  {
    id: 'a0-05-koud',
    level: 'A0',
    lessonId: 'a0/05-hebben-and-everyday-things',
    prompt: 'Fix: Ik ben het koud.',
    answer: 'Ik heb het koud.',
    tags: ['hebben', 'common-mistake'],
  },
  {
    id: 'a0-06-waar',
    level: 'A0',
    lessonId: 'a0/06-basic-questions',
    prompt: 'Translate: Where do you live?',
    answer: 'Waar woon je?',
    tags: ['questions', 'translation'],
  },
  {
    id: 'a0-07-price',
    level: 'A0',
    lessonId: 'a0/07-numbers-21-100-and-money',
    prompt: 'Translate: How much does it cost?',
    answer: 'Hoeveel kost het?',
    tags: ['money', 'questions'],
  },
  {
    id: 'a0-08-day',
    level: 'A0',
    lessonId: 'a0/08-days-months-and-dates',
    prompt: 'on Friday (Dutch)',
    answer: 'op vrijdag (days are lowercase)',
    tags: ['calendar'],
  },
  {
    id: 'a0-09-kom-uit',
    level: 'A0',
    lessonId: 'a0/09-where-do-you-live',
    prompt: 'I come from England.',
    answer: 'Ik kom uit Engeland.',
    tags: ['place', 'translation'],
  },
  {
    id: 'a0-10-order',
    level: 'A0',
    lessonId: 'a0/10-ordering-food-and-drink',
    prompt: 'A coffee, please (polite).',
    answer: 'Een koffie, alstublieft. (or alstublieft with graag patterns)',
    tags: ['food', 'politeness'],
  },
  {
    id: 'a0-11-half',
    level: 'A0',
    lessonId: 'a0/11-telling-time-and-reading-the-clock',
    prompt: 'What time is half zeven in English clock style?',
    answer: '6:30 (Dutch half = half hour TO the next hour)',
    tags: ['time'],
  },
  {
    id: 'a0-12-de-het-brood',
    level: 'A0',
    lessonId: 'a0/12-de-het-primer',
    prompt: 'Fix: de brood',
    answer: 'het brood',
    tags: ['articles', 'common-mistake'],
  },
  {
    id: 'a0-12-de-het-fiets',
    level: 'A0',
    lessonId: 'a0/12-de-het-primer',
    prompt: 'Fix: het fiets',
    answer: 'de fiets',
    tags: ['articles', 'common-mistake'],
  },
  {
    id: 'a1-02-v2',
    level: 'A1',
    lessonId: 'a1/02-word-order-svo',
    prompt: 'Today I work at home.',
    answer: 'Vandaag werk ik thuis.',
    tags: ['word-order', 'translation'],
  },
  {
    id: 'a1-03-geen',
    level: 'A1',
    lessonId: 'a1/03-negation',
    prompt: 'Fix: Ik heb niet tijd.',
    answer: 'Ik heb geen tijd.',
    tags: ['negation', 'common-mistake'],
  },
  {
    id: 'a1-05-ons-onze',
    level: 'A1',
    lessonId: 'a1/05-possessives',
    prompt: 'our house (het huis)',
    answer: 'ons huis',
    tags: ['possessives'],
  },
  {
    id: 'a1-12-modal',
    level: 'A1',
    lessonId: 'a1/12-more-present-verbs',
    prompt: 'I want to drink coffee.',
    answer: 'Ik wil koffie drinken.',
    tags: ['modals', 'word-order'],
  },
  {
    id: 'a1-18-past',
    level: 'A1',
    lessonId: 'a1/18-simple-past-regular',
    prompt: 'Yesterday I worked.',
    answer: 'Gisteren werkte ik.',
    tags: ['past', 'translation'],
  },
  {
    id: 'a1-21-separable',
    level: 'A1',
    lessonId: 'a1/21-separable-verbs',
    prompt: 'Fix: Ik opsta om zeven uur.',
    answer: 'Ik sta om zeven uur op.',
    tags: ['separable', 'common-mistake'],
  },
  {
    id: 'a2-14-omdat',
    level: 'A2',
    lessonId: 'a2/14-subordinate-want-omdat',
    prompt: 'Fix: Omdat ik ben moe, ik ga slapen.',
    answer: 'Omdat ik moe ben, ga ik slapen.',
    tags: ['omdat', 'word-order'],
  },
  {
    id: 'a2-02-perfect',
    level: 'A2',
    lessonId: 'a2/02-perfect-tense-intro',
    prompt: 'I have worked today.',
    answer: 'Ik heb vandaag gewerkt.',
    tags: ['perfect', 'translation'],
  },
  {
    id: 'a2-16-er',
    level: 'A2',
    lessonId: 'a2/16-er-constructions',
    prompt: 'There are many bikes in Amsterdam.',
    answer: 'Er zijn veel fietsen in Amsterdam.',
    tags: ['er', 'translation'],
  },
  {
    id: 'b1-01-hoewel',
    level: 'B1',
    lessonId: 'b1/01-conjunctions-overview',
    prompt: 'Fix: Hoewel ik ben moe, ik ga uit.',
    answer: 'Hoewel ik moe ben, ga ik uit.',
    tags: ['hoewel'],
  },
  {
    id: 'b1-05-zou',
    level: 'B1',
    lessonId: 'b1/05-zou-politeness-and-advice',
    prompt: 'Polite: Could you help me?',
    answer: 'Zou je me kunnen helpen?',
    tags: ['zou'],
  },
  {
    id: 'b1-06-hypo',
    level: 'B1',
    lessonId: 'b1/06-hypotheticals-with-als',
    prompt: 'If I were rich, I would travel.',
    answer: 'Als ik rijk was, zou ik reizen.',
    tags: ['als'],
  },
  {
    id: 'b1-07-past',
    level: 'B1',
    lessonId: 'b1/07-conditional-past',
    prompt: 'If I had known, I would have come.',
    answer: 'Als ik het had geweten, zou ik zijn gekomen.',
    tags: ['conditional-past'],
  },
  {
    id: 'b1-08-passive',
    level: 'B1',
    lessonId: 'b1/08-passive-with-worden',
    prompt: 'The report is being finished (ongoing).',
    answer: 'Het rapport wordt afgerond.',
    tags: ['passive'],
  },
  {
    id: 'b1-09-zijn',
    level: 'B1',
    lessonId: 'b1/09-passive-with-zijn',
    prompt: 'The window is broken (state).',
    answer: 'Het venster is gebroken.',
    tags: ['passive-zijn'],
  },
  {
    id: 'b1-10-indirect',
    level: 'B1',
    lessonId: 'b1/10-indirect-speech',
    prompt: 'He said he would come tomorrow.',
    answer: 'Hij zei dat hij de volgende dag zou komen.',
    tags: ['indirect-speech'],
  },
  {
    id: 'b1-03-waar',
    level: 'B1',
    lessonId: 'b1/03-waar-plus-preposition',
    prompt: 'The city I live in.',
    answer: 'De stad waarin ik woon.',
    tags: ['waar'],
  },
  {
    id: 'b1-12-order',
    level: 'B1',
    lessonId: 'b1/12-word-order-masterclass',
    prompt: 'Fix: Morgen ik ga werken.',
    answer: 'Morgen ga ik werken.',
    tags: ['word-order'],
  },
  {
    id: 'b1-16-formal',
    level: 'B1',
    lessonId: 'b1/16-formal-letters-and-emails',
    prompt: 'Formal email sign-off.',
    answer: 'Met vriendelijke groet,',
    tags: ['formal'],
  },
  {
    id: 'b1-27-bsn',
    level: 'B1',
    lessonId: 'b1/27-practical-netherlands',
    prompt: 'I need to register at the municipality.',
    answer: 'Ik moet me inschrijven bij de gemeente.',
    tags: ['bureaucracy'],
  },
  {
    id: 'b1-14-debate',
    level: 'B1',
    lessonId: 'b1/14-agreeing-and-debating',
    prompt: 'I see it differently.',
    answer: 'Ik zie dat anders.',
    tags: ['opinions'],
  },
  {
    id: 'a0-04-zijn-honger',
    level: 'A0',
    lessonId: 'a0/05-hebben-and-everyday-things',
    prompt: 'Fix: Ik ben honger.',
    answer: 'Ik heb honger. (pain/hunger uses hebben)',
    tags: ['hebben', 'common-mistake'],
  },
  {
    id: 'a0-06-waar-woon',
    level: 'A0',
    lessonId: 'a0/09-where-do-you-live',
    prompt: 'Where do you live?',
    answer: 'Waar woon je?',
    tags: ['questions', 'translation'],
  },
  {
    id: 'a0-10-de-koffie',
    level: 'A0',
    lessonId: 'a0/10-ordering-food-and-drink',
    prompt: 'Fix: Ik wil de koffie.',
    answer:
      'Ik wil koffie. / Een koffie, alsjeblieft. (no de for ordering some coffee)',
    tags: ['articles', 'food'],
  },
  {
    id: 'a1-03-geen-melk',
    level: 'A1',
    lessonId: 'a1/03-negation',
    prompt: 'No milk, please.',
    answer: 'Geen melk, alsjeblieft.',
    tags: ['geen', 'translation'],
  },
  {
    id: 'a1-02-v2',
    level: 'A1',
    lessonId: 'a1/02-word-order-svo',
    prompt: 'Fix: Vandaag ik werk thuis.',
    answer: 'Vandaag werk ik thuis.',
    tags: ['word-order', 'v2'],
  },
  {
    id: 'a1-06-de-brood',
    level: 'A1',
    lessonId: 'a1/06-food-and-drink',
    prompt: 'Fix: de brood',
    answer: 'het brood',
    tags: ['articles', 'de-het'],
  },
  {
    id: 'a1-10-plural',
    level: 'A1',
    lessonId: 'a1/10-plural-nouns',
    prompt: 'Plural of **de fiets**',
    answer: 'de fietsen',
    tags: ['plural'],
  },
  {
    id: 'a1-12-modal',
    level: 'A1',
    lessonId: 'a1/12-more-present-verbs',
    prompt: 'I want to drink coffee.',
    answer: 'Ik wil koffie drinken.',
    tags: ['modals', 'translation'],
  },
  {
    id: 'a1-18-past',
    level: 'A1',
    lessonId: 'a1/18-simple-past-regular',
    prompt: 'Yesterday I worked at home.',
    answer: 'Gisteren werkte ik thuis.',
    tags: ['past', 'translation'],
  },
  {
    id: 'a1-20-reflexive',
    level: 'A1',
    lessonId: 'a1/20-reflexive-verbs',
    prompt: 'I shower in the morning.',
    answer: "Ik douche 's ochtends. / Ik douche in de ochtend.",
    tags: ['reflexive', 'translation'],
  },
  {
    id: 'a2-03-participle',
    level: 'A2',
    lessonId: 'a2/03-perfect-irregular',
    prompt: 'We have eaten.',
    answer: 'Wij hebben gegeten.',
    tags: ['perfect', 'translation'],
  },
  {
    id: 'a2-05-vinden',
    level: 'A2',
    lessonId: 'a2/05-opinions',
    prompt: 'I think the film is interesting.',
    answer: 'Ik vind de film interessant.',
    tags: ['opinions', 'translation'],
  },
  {
    id: 'a2-06-beter',
    level: 'A2',
    lessonId: 'a2/06-comparatives',
    prompt: 'Fix: meer better',
    answer: 'beter',
    tags: ['comparatives', 'common-mistake'],
  },
  {
    id: 'a2-12-die',
    level: 'A2',
    lessonId: 'a2/12-relative-clauses',
    prompt: 'Fix: de man dat ik ken',
    answer: 'de man die ik ken',
    tags: ['relative', 'common-mistake'],
  },
  {
    id: 'a2-15-me',
    level: 'A2',
    lessonId: 'a2/15-indirect-objects',
    prompt: 'He gives me the book.',
    answer: 'Hij geeft me het boek. / Hij geeft het boek aan mij.',
    tags: ['indirect-object', 'translation'],
  },
  {
    id: 'a2-19-afspraak',
    level: 'A2',
    lessonId: 'a2/19-appointments',
    prompt: 'Can we reschedule the appointment?',
    answer: 'Kunnen we de afspraak verzetten?',
    tags: ['appointments', 'translation'],
  },
  {
    id: 'a2-21-worden',
    level: 'A2',
    lessonId: 'a2/21-passive-intro',
    prompt: 'The house is being built (ongoing).',
    answer: 'Het huis wordt gebouwd.',
    tags: ['passive', 'translation'],
  },
  {
    id: 'b1-02-wiens',
    level: 'B1',
    lessonId: 'b1/02-relative-clauses',
    prompt: 'The colleague whose car is red.',
    answer: 'De collega wiens auto rood is.',
    tags: ['relative', 'translation'],
  },
  {
    id: 'b1-04-zullen',
    level: 'B1',
    lessonId: 'b1/04-future-with-zullen',
    prompt: 'Shall we meet tomorrow?',
    answer: 'Zullen we morgen afspreken?',
    tags: ['future', 'translation'],
  },
  {
    id: 'b1-10-reported',
    level: 'B1',
    lessonId: 'b1/10-indirect-speech',
    prompt: 'She said she was ill.',
    answer: 'Zij zei dat ze ziek was.',
    tags: ['indirect-speech', 'translation'],
  },
  {
    id: 'b1-11-te',
    level: 'B1',
    lessonId: 'b1/11-te-plus-infinitive',
    prompt: 'It is hard to say.',
    answer: 'Het is moeilijk te zeggen.',
    tags: ['te', 'translation'],
  },
  {
    id: 'b1-13-mening',
    level: 'B1',
    lessonId: 'b1/13-nuanced-opinions',
    prompt: 'In my opinion, …',
    answer: 'Naar mijn mening, …',
    tags: ['opinions', 'translation'],
  },
  {
    id: 'b1-22-story',
    level: 'B1',
    lessonId: 'b1/22-storytelling-past-tenses',
    prompt: 'I had just come home when …',
    answer: 'Ik was net thuisgekomen toen …',
    tags: ['past', 'translation'],
  },
  {
    id: 'b1-24-maar',
    level: 'B1',
    lessonId: 'b1/24-particles-masterclass',
    prompt: 'Come on in. (welcoming)',
    answer: 'Kom maar binnen.',
    tags: ['particles', 'translation'],
  },
  {
    id: 'sc-a1-train',
    level: 'A1',
    lessonId: 'a1/15-transport',
    prompt: 'One ticket to Utrecht, please.',
    answer: 'Een ticket naar Utrecht, alstublieft.',
    tags: ['scenario', 'transport'],
  },
  {
    id: 'sc-a2-hotel',
    level: 'A2',
    lessonId: 'a2/09-describing-places',
    prompt: 'I booked a room for two nights.',
    answer: 'Ik heb een kamer gereserveerd voor twee nachten.',
    tags: ['scenario', 'hotel'],
  },
  {
    id: 'sc-b1-gemeente',
    level: 'B1',
    lessonId: 'b1/27-practical-netherlands',
    prompt: 'Where can I report my move?',
    answer: 'Waar kan ik mijn verhuizing doorgeven?',
    tags: ['scenario', 'bureaucracy'],
  },
  {
    id: 'a0-08-dag',
    level: 'A0',
    lessonId: 'a0/08-days-months-and-dates',
    prompt: 'What day is it today? (pattern)',
    answer: 'Welke dag is het vandaag? / Het is maandag.',
    tags: ['days', 'questions'],
  },
  {
    id: 'a0-11-half',
    level: 'A0',
    lessonId: 'a0/11-telling-time-and-reading-the-clock',
    prompt: 'half acht means what time?',
    answer: '7:30 (half toward eight, not 8:30 English-style)',
    tags: ['time', 'culture'],
  },
  {
    id: 'a1-07-restaurant',
    level: 'A1',
    lessonId: 'a1/07-at-the-restaurant',
    prompt: 'The bill, please.',
    answer: 'De rekening, alstublieft.',
    tags: ['restaurant', 'translation'],
  },
  {
    id: 'a1-08-shopping',
    level: 'A1',
    lessonId: 'a1/08-shopping',
    prompt: 'How much does this cost?',
    answer: 'Hoeveel kost dit? / Wat kost dit?',
    tags: ['shopping', 'translation'],
  },
  {
    id: 'a1-15-train',
    level: 'A1',
    lessonId: 'a1/15-transport',
    prompt: 'Where is the train to Amsterdam?',
    answer: 'Waar is de trein naar Amsterdam?',
    tags: ['transport', 'translation'],
  },
  {
    id: 'a1-17-headache',
    level: 'A1',
    lessonId: 'a1/17-body-health',
    prompt: 'Fix: Ik ben hoofdpijn.',
    answer: 'Ik heb hoofdpijn.',
    tags: ['health', 'hebben'],
  },
  {
    id: 'a2-04-moet',
    level: 'A2',
    lessonId: 'a2/04-modals-in-depth',
    prompt: 'You must register today.',
    answer: 'Je moet vandaag inschrijven. / U moet vandaag inschrijven.',
    tags: ['modals', 'translation'],
  },
  {
    id: 'a2-07-super',
    level: 'A2',
    lessonId: 'a2/07-superlatives',
    prompt: 'the most interesting',
    answer: 'het interessantst / het meest interessant',
    tags: ['superlatives', 'translation'],
  },
  {
    id: 'a2-11-time',
    level: 'A2',
    lessonId: 'a2/11-prepositions-time',
    prompt: 'on Monday / on Mondays',
    answer: 'op maandag (single day)',
    tags: ['prepositions', 'time'],
  },
  {
    id: 'a2-20-als',
    level: 'A2',
    lessonId: 'a2/20-conditional-als',
    prompt: 'If it rains, I stay home.',
    answer: 'Als het regent, blijf ik thuis.',
    tags: ['als', 'translation'],
  },
  {
    id: 'b1-01-hoewel',
    level: 'B1',
    lessonId: 'b1/01-conjunctions-overview',
    prompt: 'Although I am tired, I will continue.',
    answer: 'Hoewel ik moe ben, ga ik door.',
    tags: ['hoewel', 'translation'],
  },
  {
    id: 'b1-09-zijn-pass',
    level: 'B1',
    lessonId: 'b1/09-passive-with-zijn',
    prompt: 'The door is closed (state).',
    answer: 'De deur is gesloten.',
    tags: ['passive', 'zijn'],
  },
  {
    id: 'b1-20-feel',
    level: 'B1',
    lessonId: 'b1/20-feelings-and-relationships',
    prompt: 'I feel stressed.',
    answer: 'Ik voel me gestrest.',
    tags: ['feelings', 'translation'],
  },
  {
    id: 'b1-25-idiom',
    level: 'B1',
    lessonId: 'b1/25-idioms-and-expressions',
    prompt: 'It is raining heavily (Dutch idiom).',
    answer: 'Het regent pijpenstelen.',
    tags: ['idioms', 'translation'],
  },
  {
    id: 'rev-a0-greet',
    level: 'A0',
    lessonId: 'a0/01-greetings-and-introductions',
    prompt: 'Good evening (18:00 greeting).',
    answer: 'Goedenavond',
    tags: ['review', 'greetings'],
  },
  {
    id: 'rev-a1-niet',
    level: 'A1',
    lessonId: 'a1/03-negation',
    prompt: 'I do not work today.',
    answer: 'Ik werk vandaag niet.',
    tags: ['review', 'negation'],
  },
  {
    id: 'rev-a2-perfect',
    level: 'A2',
    lessonId: 'a2/02-perfect-tense-intro',
    prompt: 'Fix: Ik ben gisteren gewerkt (no movement).',
    answer: 'Ik heb gisteren gewerkt.',
    tags: ['review', 'perfect'],
  },
  {
    id: 'rev-b1-zou',
    level: 'B1',
    lessonId: 'b1/05-zou-politeness-and-advice',
    prompt: 'Could you help me? (polite)',
    answer: 'Zou u me kunnen helpen? / Zou je me kunnen helpen?',
    tags: ['review', 'zou'],
  },
];

export function getDrillQuestionsForLevel(
  level: DrillQuestion['level']
): DrillQuestion[] {
  return DRILL_QUESTIONS.filter((q) => q.level === level);
}

export function getDrillQuestionsForLesson(lessonId: string): DrillQuestion[] {
  return DRILL_QUESTIONS.filter((q) => q.lessonId === lessonId);
}
