export type FlashcardItem = {
  front: string;
  back: string;
  example?: string;
};

export const LESSON_FLASHCARDS: Record<string, FlashcardItem[]> = {
  'a0/01-greetings-and-introductions': [
    { front: 'Hoe heet je?', back: 'What is your name?' },
    { front: 'Goedemorgen', back: 'Good morning' },
    { front: 'Goedenavond', back: 'Good evening' },
    { front: 'Tot ziens', back: 'Goodbye (polite)' },
    { front: 'Aangenaam', back: 'Nice to meet you' },
    { front: 'Ik ben …', back: 'I am …' },
  ],
  'a0/02-alphabet-and-spelling': [
    { front: 'Hoe spel je dat?', back: 'How do you spell that?' },
    { front: 'Langzaam, alsjeblieft', back: 'Slowly, please' },
    { front: 'Ik begrijp het niet', back: 'I do not understand' },
    { front: 'Kunt u dat spellen?', back: 'Can you spell that?' },
    { front: 'de maan', back: 'the moon (long aa)' },
    { front: 'de man', back: 'the man (short a)' },
  ],
  'a0/03-numbers-0-20-and-age': [
    { front: 'Hoe oud ben je?', back: 'How old are you?' },
    { front: 'Ik ben twintig jaar', back: 'I am twenty years old' },
    { front: 'vijftien', back: 'fifteen' },
    { front: 'nul', back: 'zero' },
    { front: 'dertien', back: 'thirteen' },
    { front: 'achttien', back: 'eighteen' },
  ],
  'a0/04-pronouns-and-zijn': [
    { front: 'Hoe gaat het?', back: 'How are you? (How goes it?)' },
    { front: 'u / u bent', back: 'formal you / you are (formal)' },
    { front: 'wij zijn', back: 'we are' },
    { front: 'jij bent', back: 'you are (informal)' },
    { front: 'zij is', back: 'she is' },
    { front: 'zij zijn', back: 'they are' },
  ],
  'a0/05-hebben-and-everyday-things': [
    { front: 'Ik heb honger', back: 'I am hungry (lit. I have hunger)' },
    { front: 'Ik heb dorst', back: 'I am thirsty' },
    { front: 'Ik heb het koud', back: 'I am cold' },
    { front: 'Heb jij …?', back: 'Do you have …?' },
    { front: 'Ik heb een fiets', back: 'I have a bicycle' },
    { front: 'Ik heb geen tijd', back: 'I have no time' },
  ],
  'a0/06-basic-questions': [
    { front: 'wie', back: 'who' },
    { front: 'wat', back: 'what' },
    { front: 'waar', back: 'where' },
    { front: 'wanneer', back: 'when' },
    { front: 'waarom', back: 'why' },
    { front: 'hoe', back: 'how' },
  ],
  'a0/07-numbers-21-100-and-money': [
    { front: 'Hoeveel kost het?', back: 'How much does it cost?' },
    { front: 'vijfentwintig', back: 'twenty-five' },
    { front: 'tachtig', back: 'eighty' },
    { front: 'het geld', back: 'the money' },
    { front: 'euro', back: 'euro' },
    { front: 'tweehonderd', back: 'two hundred' },
  ],
  'a0/08-days-months-and-dates': [
    { front: 'op maandag', back: 'on Monday' },
    { front: 'in mei', back: 'in May' },
    { front: 'het weekend', back: 'the weekend' },
    { front: 'vandaag', back: 'today' },
    { front: 'morgen', back: 'tomorrow' },
    { front: 'gisteren', back: 'yesterday' },
  ],
  'a0/09-where-do-you-live': [
    { front: 'Ik woon in …', back: 'I live in …' },
    { front: 'Ik kom uit …', back: 'I come from …' },
    { front: 'Waar woon je?', back: 'Where do you live?' },
    { front: 'de stad', back: 'the city' },
    { front: 'het dorp', back: 'the village' },
    { front: 'Nederland', back: 'the Netherlands' },
  ],
  'a0/10-ordering-food-and-drink': [
    { front: 'Ik wil graag …', back: 'I would like … (polite)' },
    { front: 'de rekening, alstublieft', back: 'the bill, please' },
    { front: 'het brood', back: 'the bread' },
    { front: 'de koffie', back: 'the coffee' },
    { front: 'het water', back: 'the water' },
    { front: 'Mag ik …?', back: 'May I have …?' },
  ],
  'a0/11-telling-time-and-reading-the-clock': [
    { front: 'Hoe laat is het?', back: 'What time is it?' },
    { front: 'half zeven', back: '6:30 (Dutch half rule)' },
    { front: 'kwart over acht', back: 'quarter past eight' },
    { front: 'om acht uur', back: "at eight o'clock" },
    { front: 'te laat', back: 'late' },
    { front: 'op tijd', back: 'on time' },
  ],
  'a0/12-de-het-primer': [
    { front: 'het brood', back: 'the bread (het word)' },
    { front: 'de fiets', back: 'the bicycle (de word)' },
    { front: 'de koffie', back: 'the coffee' },
    { front: 'het water', back: 'the water' },
    { front: 'de taal', back: 'the language' },
    { front: 'het huis', back: 'the house' },
  ],
  'a1/01-daily-routines': [
    { front: 'Ik sta om zeven uur op', back: 'I get up at seven' },
    { front: 'Wat doe je vandaag?', back: 'What are you doing today?' },
    { front: 'altijd', back: 'always' },
    { front: 'meestal', back: 'usually' },
    { front: 'soms', back: 'sometimes' },
    { front: 'nooit', back: 'never' },
  ],
  'a1/02-word-order-svo': [
    { front: 'Vandaag werk ik thuis', back: 'Today I work at home (V2)' },
    { front: 'Werk jij vandaag?', back: 'Do you work today?' },
    { front: 'Morgen ga ik naar school', back: 'Tomorrow I go to school' },
    { front: 'Ik eet thuis', back: 'I eat at home' },
    { front: 'Waar woon je?', back: 'Where do you live?' },
    { front: 'niet', back: 'not' },
  ],
  'a1/03-negation': [
    { front: 'Ik heb geen tijd', back: 'I have no time' },
    { front: 'Ik werk niet', back: 'I do not work' },
    { front: 'Ik sta niet op', back: 'I do not get up' },
    { front: 'geen melk', back: 'no milk (indefinite noun)' },
    { front: 'niet vandaag', back: 'not today' },
    { front: 'Heb je geen honger?', back: 'Are you not hungry?' },
  ],
  'a1/04-family': [
    { front: 'de moeder', back: 'mother' },
    { front: 'de vader', back: 'father' },
    { front: 'Ik heb geen kinderen', back: 'I have no children' },
    { front: 'Dit is mijn zus', back: 'This is my sister' },
    { front: 'de broer', back: 'brother' },
    { front: 'de familie', back: 'the family' },
  ],
  'a1/05-possessives': [
    { front: 'mijn moeder', back: 'my mother' },
    { front: 'jouw fiets', back: 'your bicycle' },
    { front: 'zijn auto', back: 'his car' },
    { front: 'haar tas', back: 'her bag' },
    { front: 'ons huis', back: 'our house (het word)' },
    { front: 'onze fiets', back: 'our bicycle (de word)' },
  ],
  'a1/06-food-and-drink': [
    { front: 'de melk', back: 'the milk' },
    { front: 'het brood', back: 'the bread' },
    { front: 'Ik wil graag …', back: 'I would like …' },
    { front: 'de appel', back: 'the apple' },
    { front: 'het fruit', back: 'the fruit' },
    { front: 'de kaas', back: 'the cheese' },
  ],
  'a1/07-at-the-restaurant': [
    { front: 'Mag ik de menukaart?', back: 'May I have the menu?' },
    { front: 'de rekening, alstublieft', back: 'the bill, please' },
    { front: 'Ik zou graag …', back: 'I would like … (polite)' },
    { front: 'Het smaakt goed', back: 'It tastes good' },
    { front: 'Nog iets te drinken?', back: 'Anything else to drink?' },
    { front: 'de ober / de serveerster', back: 'waiter / waitress' },
  ],
  'a1/08-shopping': [
    { front: 'Hoeveel kost het?', back: 'How much does it cost?' },
    { front: 'Ik wil graag betalen', back: 'I would like to pay' },
    { front: 'deze jas', back: 'this coat' },
    { front: 'die schoenen', back: 'those shoes' },
    { front: 'Te duur', back: 'Too expensive' },
    { front: 'Hebt u maat M?', back: 'Do you have size M?' },
  ],
  'a1/09-demonstratives': [
    { front: 'deze tafel', back: 'this table (de word)' },
    { front: 'dit boek', back: 'this book (het word)' },
    { front: 'die jas', back: 'that coat' },
    { front: 'dat huis', back: 'that house' },
    { front: 'Is dit van jou?', back: 'Is this yours?' },
    { front: 'Welke wil je?', back: 'Which one do you want?' },
  ],
  'a1/10-plural-nouns': [
    { front: 'de boeken', back: 'the books' },
    { front: 'de kinderen', back: 'the children' },
    { front: "de auto's", back: 'the cars (+s plural)' },
    { front: 'de stoelen', back: 'the chairs (+en plural)' },
    { front: 'de eieren', back: 'the eggs' },
    { front: 'de fietsen', back: 'the bicycles' },
  ],
  'a1/11-adjectives': [
    { front: 'De stad is groot', back: 'The city is big (no -e after zijn)' },
    { front: 'de grote stad', back: 'the big city (-e with de)' },
    { front: 'het grote huis', back: 'the big house (-e with het + de adj)' },
    { front: 'een mooi huis', back: 'a beautiful house (indefinite het)' },
    { front: 'Het weer is slecht', back: 'The weather is bad' },
    { front: 'de kleine kamer', back: 'the small room' },
  ],
  'a1/12-more-present-verbs': [
    { front: 'Ik wil koffie drinken', back: 'I want to drink coffee' },
    { front: 'Ik kan niet komen', back: 'I cannot come' },
    { front: 'Ik moet werken', back: 'I have to work' },
    { front: 'Kun je me helpen?', back: 'Can you help me?' },
    { front: 'Ik mag niet roken', back: 'I am not allowed to smoke' },
    { front: 'Ik lees een boek', back: 'I read a book' },
  ],
  'a1/13-housing': [
    { front: 'Ik woon in een flat', back: 'I live in a flat' },
    { front: 'de woonkamer', back: 'the living room' },
    { front: 'de slaapkamer', back: 'the bedroom' },
    { front: 'de keuken', back: 'the kitchen' },
    { front: 'Het boek ligt op de tafel', back: 'The book is on the table' },
    {
      front: 'De lamp hangt aan het plafond',
      back: 'The lamp hangs from the ceiling',
    },
  ],
  'a1/14-hobbies': [
    { front: 'Ik hou van lezen', back: 'I like reading' },
    { front: 'In mijn vrije tijd …', back: 'In my free time …' },
    { front: 'Ik sport graag', back: 'I like to exercise' },
    { front: 'Ik luister naar muziek', back: 'I listen to music' },
    { front: 'Ik speel gitaar', back: 'I play guitar' },
    { front: 'Wat doe je graag?', back: 'What do you like to do?' },
  ],
  'a1/15-transport': [
    {
      front: 'Hoe kom ik bij het station?',
      back: 'How do I get to the station?',
    },
    { front: 'links', back: 'left' },
    { front: 'rechts', back: 'right' },
    { front: 'rechtdoor', back: 'straight ahead' },
    { front: 'de trein', back: 'the train' },
    { front: 'de OV-chipkaart', back: 'the OV chip card (public transport)' },
  ],
  'a1/16-weather': [
    { front: 'Het regent', back: 'It is raining' },
    { front: 'Het is warm', back: 'It is warm' },
    { front: 'Het is koud', back: 'It is cold' },
    { front: 'Ik heb het warm', back: 'I am warm (lit. I have it warm)' },
    { front: 'Het waait', back: 'It is windy' },
    { front: 'Het is zonnig', back: 'It is sunny' },
  ],
  'a1/17-body-health': [
    { front: 'Ik ben ziek', back: 'I am ill' },
    { front: 'Ik heb hoofdpijn', back: 'I have a headache' },
    { front: 'de dokter', back: 'doctor' },
    { front: 'de apotheek', back: 'pharmacy' },
    { front: 'Ik voel me niet goed', back: 'I do not feel well' },
    { front: 'Waar doet het pijn?', back: 'Where does it hurt?' },
  ],
  'a1/18-simple-past-regular': [
    { front: 'ik werkte', back: 'I worked (regular past)' },
    { front: 'Gisteren werkte ik thuis', back: 'Yesterday I worked at home' },
    { front: 'ik woonde', back: 'I lived' },
    { front: 'ik speelde', back: 'I played' },
    { front: 'ik luisterde', back: 'I listened' },
    { front: 'ik maakte', back: 'I made' },
  ],
  'a1/19-simple-past-irregular': [
    { front: 'Ik ging naar huis', back: 'I went home' },
    { front: 'Ik kwam laat', back: 'I came late' },
    { front: 'Ik had geen tijd', back: 'I had no time' },
    { front: 'Ik was moe', back: 'I was tired' },
    { front: 'Ik zag hem gisteren', back: 'I saw him yesterday' },
    { front: 'Hij zei nee', back: 'He said no' },
  ],
  'a1/20-reflexive-verbs': [
    { front: 'Ik was me', back: 'I wash myself / I shower' },
    { front: 'Ik kleed me aan', back: 'I get dressed' },
    { front: 'Ik scheren me', back: 'I shave' },
    { front: 'Ik voel me goed', back: 'I feel good' },
    { front: 'Hij scheert zich', back: 'He shaves (formal/reflexive)' },
    { front: 'Wij wassen ons', back: 'We wash ourselves' },
  ],
  'a1/21-separable-verbs': [
    { front: 'Ik sta om zeven uur op', back: 'I get up at seven (op at end)' },
    { front: 'Ik bel je morgen op', back: 'I will call you tomorrow' },
    { front: 'Ik wil niet opstaan', back: 'I do not want to get up' },
    { front: 'uitgaan', back: 'to go out' },
    { front: 'meekomen', back: 'to come along' },
    { front: 'aankomen', back: 'to arrive' },
  ],
  'a2/01-past-tense-depth': [
    { front: 'Ik werkte gisteren', back: 'I worked yesterday' },
    {
      front: 'Toen woonde ik in Utrecht',
      back: 'Back then I lived in Utrecht',
    },
    { front: 'Vertel eens!', back: 'Tell me! (story prompt)' },
    { front: 'Ik luisterde naar muziek', back: 'I listened to music' },
    { front: 'Wij speelden voetbal', back: 'We played football' },
    { front: 'Het regende de hele dag', back: 'It rained all day' },
  ],
  'a2/02-perfect-tense-intro': [
    { front: 'Ik heb gewerkt', back: 'I have worked / I worked (spoken)' },
    { front: 'Ik ben gegaan', back: 'I went (zijn + movement)' },
    { front: 'Ik heb gegeten', back: 'I have eaten' },
    { front: 'Ben je klaar?', back: 'Are you ready?' },
    { front: 'Wij zijn thuisgekomen', back: 'We have come home' },
    { front: 'Ik heb het boek gelezen', back: 'I have read the book' },
  ],
  'a2/03-perfect-irregular': [
    { front: 'gegaan', back: 'gone (participle)' },
    { front: 'gezien', back: 'seen (participle)' },
    { front: 'gehad', back: 'had (participle)' },
    { front: 'Ik ben gegaan', back: 'I went' },
    { front: 'Ik heb gekocht', back: 'I have bought' },
    { front: 'Ik heb geschreven', back: 'I have written' },
  ],
  'a2/04-modals-in-depth': [
    { front: 'Ik moet morgen werken', back: 'I have to work tomorrow' },
    { front: 'Dat mag niet', back: 'That is not allowed' },
    { front: 'Zullen we afspreken?', back: 'Shall we meet?' },
    {
      front: 'Ik heb moeten werken',
      back: 'I had to work (double infinitive)',
    },
    { front: 'Mag ik hier zitten?', back: 'May I sit here?' },
    { front: 'Ik zou graag willen', back: 'I would like to (polite preview)' },
  ],
  'a2/05-opinions': [
    { front: 'Ik vind dat …', back: 'I think that …' },
    { front: 'Volgens mij', back: 'In my opinion' },
    { front: 'Ik ben het eens met', back: 'I agree with' },
    { front: 'Ik ben het niet eens', back: 'I disagree' },
    { front: 'Dat klopt', back: 'That is correct' },
    { front: 'Ik denk van wel', back: 'I think so' },
  ],
  'a2/06-comparatives': [
    { front: 'groter', back: 'bigger' },
    { front: 'beter', back: 'better (irregular)' },
    { front: 'meer … dan', back: 'more … than' },
    { front: 'minder … dan', back: 'less … than' },
    {
      front: 'Amsterdam is groter dan Utrecht',
      back: 'Amsterdam is bigger than Utrecht',
    },
    { front: 'Dit is beter', back: 'This is better' },
  ],
  'a2/07-superlatives': [
    { front: 'het grootst', back: 'the biggest' },
    { front: 'het best', back: 'the best (irregular)' },
    { front: 'de meest interessante', back: 'the most interesting' },
    { front: 'Het mooiste is …', back: 'The best part is …' },
    { front: 'de kleinste', back: 'the smallest' },
    { front: 'de minst duur', back: 'the least expensive' },
  ],
  'a2/08-describing-people': [
    { front: 'Hij is lang', back: 'He is tall' },
    { front: 'Ze heeft blauwe ogen', back: 'She has blue eyes' },
    { front: 'vriendelijk', back: 'friendly' },
    { front: 'serieus', back: 'serious' },
    { front: 'Hij heeft blond haar', back: 'He has blond hair' },
    { front: 'Ze is aardig', back: 'She is nice' },
  ],
  'a2/09-describing-places': [
    { front: 'Het is druk', back: 'It is busy' },
    { front: 'Het is rustig', back: 'It is quiet' },
    { front: 'in het centrum', back: 'in the city centre' },
    { front: 'Er zijn veel cafés', back: 'There are many cafés' },
    { front: 'De stad is mooi', back: 'The city is beautiful' },
    { front: 'Het park is groot', back: 'The park is big' },
  ],
  'a2/10-prepositions-place': [
    { front: 'op de tafel', back: 'on the table' },
    { front: 'in de kamer', back: 'in the room' },
    { front: 'aan de deur', back: 'on/at the door' },
    { front: 'bij de ingang', back: 'at the entrance' },
    { front: 'naast de bank', back: 'next to the sofa' },
    { front: 'tegenover het station', back: 'opposite the station' },
  ],
  'a2/11-prepositions-time': [
    { front: 'op maandag', back: 'on Monday' },
    { front: 'in mei', back: 'in May' },
    { front: 'van … tot …', back: 'from … to …' },
    { front: 'sinds gisteren', back: 'since yesterday' },
    { front: 'om acht uur', back: "at eight o'clock" },
    { front: 'voor het eten', back: 'before dinner' },
  ],
  'a2/12-relative-clauses': [
    { front: 'de man die …', back: 'the man who …' },
    { front: 'het boek dat …', back: 'the book that … (het → dat)' },
    { front: 'de vrouw die ik ken', back: 'the woman I know' },
    { front: 'het huis dat we kopen', back: 'the house we are buying' },
    {
      front: 'Mijn broer, die in Groningen woont, …',
      back: 'My brother, who lives in Groningen, …',
    },
    { front: 'alles wat', back: 'everything that' },
  ],
  'a2/13-om-te': [
    {
      front: 'Ik leer om Nederlands te praten',
      back: 'I learn in order to speak Dutch',
    },
    { front: 'Ik kom om te helpen', back: 'I come to help' },
    { front: 'om … te …', back: 'in order to …' },
    { front: 'Ik werk om geld te verdienen', back: 'I work to earn money' },
    { front: 'Hij studeert om te slagen', back: 'He studies in order to pass' },
    { front: 'Wij reizen om te leren', back: 'We travel to learn' },
  ],
  'a2/14-subordinate-want-omdat': [
    {
      front: 'Ik blijf thuis omdat ik ziek ben',
      back: 'I stay home because I am ill',
    },
    {
      front: 'Ik eet thuis, want ik heb geen tijd',
      back: 'I eat at home, for I have no time',
    },
    { front: 'omdat …', back: 'because (verb at end)' },
    { front: 'want …', back: 'for / because (keeps V2)' },
    {
      front: 'Ik ga niet, omdat ik moe ben',
      back: 'I am not going because I am tired',
    },
    {
      front: 'Hij komt niet, want hij is ziek',
      back: 'He is not coming, for he is ill',
    },
  ],
  'a2/15-indirect-objects': [
    { front: 'Ik geef hem het boek', back: 'I give him the book' },
    { front: 'Geef me het', back: 'Give it to me' },
    { front: 'Leg het me uit', back: 'Explain it to me' },
    { front: 'Ik bel je morgen', back: 'I will call you tomorrow' },
    { front: 'Kun je me helpen?', back: 'Can you help me?' },
    { front: 'Ik stuur haar een e-mail', back: 'I send her an email' },
  ],
  'a2/16-er-constructions': [
    { front: 'Er zijn veel mensen', back: 'There are many people' },
    { front: 'Er is geen tijd', back: 'There is no time' },
    { front: 'Is er een museum?', back: 'Is there a museum?' },
    { front: 'Ik heb er drie', back: 'I have three (of them)' },
    { front: 'Waar praat je over?', back: 'What are you talking about?' },
    { front: 'Daar praat ik over', back: 'That is what I am talking about' },
  ],
  'a2/17-workplace': [
    { front: 'de vergadering', back: 'the meeting' },
    { front: 'Ik heb een deadline', back: 'I have a deadline' },
    { front: 'thuiswerken', back: 'work from home' },
    { front: 'de baas', back: 'the boss' },
    { front: 'Ik ben op kantoor', back: 'I am at the office' },
    { front: 'Ik heb een drukke week', back: 'I have a busy week' },
  ],
  'a2/18-culture-traditions': [
    { front: 'Koningsdag', back: "King's Day (27 April)" },
    { front: 'Sinterklaas', back: '5 December tradition' },
    { front: 'gezellig', back: 'cosy / fun together' },
    { front: 'de oliebol', back: 'Dutch doughnut (New Year)' },
    { front: 'Het is feest', back: 'It is a celebration' },
    { front: 'Proost!', back: 'Cheers!' },
  ],
  'a2/19-appointments': [
    { front: 'afspraak maken', back: 'make an appointment' },
    { front: 'afspraak verzetten', back: 'reschedule an appointment' },
    { front: 'Heeft u tijd op …?', back: 'Do you have time on …?' },
    { front: 'Ik kan niet komen', back: 'I cannot come' },
    { front: 'Wanneer past het u?', back: 'When suits you?' },
    { front: 'Ik bevestig de afspraak', back: 'I confirm the appointment' },
  ],
  'a2/20-conditional-als': [
    {
      front: 'Als ik tijd heb, bel ik je',
      back: 'If I have time, I will call you',
    },
    {
      front: 'Als het regent, blijf ik thuis',
      back: 'If it rains, I stay home',
    },
    { front: 'Als je hulp nodig hebt, …', back: 'If you need help, …' },
    {
      front: 'Als het morgen mooi is, …',
      back: 'If the weather is nice tomorrow, …',
    },
    { front: 'Als ik kan, kom ik', back: 'If I can, I will come' },
    { front: 'tenzij', back: 'unless' },
  ],
  'a2/21-passive-intro': [
    { front: 'Het huis wordt gebouwd', back: 'The house is being built' },
    { front: 'Er wordt gewerkt', back: 'Work is being done' },
    { front: 'De deur wordt geopend', back: 'The door is being opened' },
    {
      front: 'Het wordt morgen afgerond',
      back: 'It will be finished tomorrow',
    },
    { front: 'De taart wordt gemaakt', back: 'The cake is being made' },
    {
      front: 'Er wordt veel gepraat',
      back: 'There is a lot of talking going on',
    },
  ],
  'b1/01-conjunctions-overview': [
    { front: 'hoewel ik moe ben', back: 'although I am tired (verb last)' },
    { front: 'terwijl ik kook', back: 'while I cook' },
    { front: 'nadat we hebben gegeten', back: 'after we have eaten' },
    { front: 'voordat hij komt', back: 'before he comes' },
    { front: 'totdat ik klaar ben', back: 'until I am ready' },
    { front: 'tenzij het regent', back: 'unless it rains' },
  ],
  'b1/02-relative-clauses': [
    { front: 'de man wiens auto …', back: 'the man whose car …' },
    {
      front: 'het boek waarvan ik het begin',
      back: 'the book of which I know the beginning',
    },
    { front: 'waarmee', back: 'with which' },
    { front: 'de collega met wie ik werk', back: 'the colleague I work with' },
    { front: 'alles wat je zegt', back: 'everything you say' },
    { front: 'de stad waar ik woon', back: 'the city where I live' },
  ],
  'b1/03-waar-plus-preposition': [
    {
      front: 'Het punt waarover we praten',
      back: 'The point we are talking about',
    },
    { front: 'waarover', back: 'about which' },
    { front: 'waarin', back: 'in which' },
    { front: 'waarnaar', back: 'to which' },
    { front: 'de reden waarom', back: 'the reason why' },
    { front: 'de persoon van wie', back: 'the person from whom' },
  ],
  'b1/04-future-with-zullen': [
    { front: 'Ik zal je morgen bellen', back: 'I will call you tomorrow' },
    { front: 'Zullen we afspreken?', back: 'Shall we meet?' },
    {
      front: 'Ik ga morgen werken',
      back: 'I am going to work tomorrow (spoken default)',
    },
    {
      front: 'De trein vertrekt om acht uur',
      back: 'The train leaves at eight (present for schedule)',
    },
    { front: 'Zal ik de deur openen?', back: 'Shall I open the door?' },
    { front: 'Wij zullen zien', back: 'We shall see' },
  ],
  'b1/05-zou-politeness-and-advice': [
    { front: 'Zou je me kunnen helpen?', back: 'Could you help me? (polite)' },
    { front: 'Ik zou wachten', back: 'I would wait (soft advice)' },
    {
      front: 'Zou u dat kunnen uitleggen?',
      back: 'Could you explain that? (formal)',
    },
    { front: 'Ik zou graag een koffie', back: 'I would like a coffee' },
    { front: 'Dat zou kunnen', back: 'That could be' },
    {
      front: 'Zou je even kunnen komen?',
      back: 'Could you come for a moment?',
    },
  ],
  'b1/06-hypotheticals-with-als': [
    {
      front: 'Als ik rijk was, zou ik reizen',
      back: 'If I were rich, I would travel',
    },
    {
      front: 'Als ik tijd had, zou ik komen',
      back: 'If I had time, I would come',
    },
    { front: 'Als ik jou was, …', back: 'If I were you, …' },
    { front: 'Ik zou graag willen', back: 'I would like to' },
    { front: 'Dat zou fijn zijn', back: 'That would be nice' },
    { front: 'Stel dat …', back: 'Suppose that …' },
  ],
  'b1/07-conditional-past': [
    {
      front: 'Als ik het had geweten, zou ik zijn gekomen',
      back: 'If I had known, I would have come',
    },
    {
      front: 'Als ik eerder was begonnen, …',
      back: 'If I had started earlier, …',
    },
    {
      front: 'Ik zou het anders hebben gedaan',
      back: 'I would have done it differently',
    },
    { front: 'Dat had ik niet verwacht', back: 'I had not expected that' },
    { front: 'Als we hadden geweten …', back: 'If we had known …' },
    { front: 'Hij zou zijn gebleven', back: 'He would have stayed' },
  ],
  'b1/08-passive-with-worden': [
    {
      front: 'Het rapport wordt afgerond',
      back: 'The report is being finished',
    },
    { front: 'Er wordt hard gewerkt', back: 'People are working hard' },
    {
      front: 'De brug werd gebouwd',
      back: 'The bridge was being built (past)',
    },
    {
      front: 'Het huis wordt door hen verkocht',
      back: 'The house is being sold by them',
    },
    { front: 'De wet wordt aangenomen', back: 'The law is being passed' },
    {
      front: 'Er wordt veel gediscussieerd',
      back: 'There is a lot of discussion',
    },
  ],
  'b1/09-passive-with-zijn': [
    {
      front: 'Het rapport is afgerond',
      back: 'The report has been finished (state)',
    },
    { front: 'Het venster is gebroken', back: 'The window is broken' },
    { front: 'De deur is gesloten', back: 'The door is closed' },
    { front: 'Het eten is klaar', back: 'The food is ready' },
    { front: 'De beslissing is genomen', back: 'The decision has been made' },
    { front: 'Alles is geregeld', back: 'Everything is arranged' },
  ],
  'b1/10-indirect-speech': [
    { front: 'Hij zei dat hij ziek was', back: 'He said he was ill' },
    { front: 'Hij zei dat hij zou komen', back: 'He said he would come' },
    { front: 'Ze vroeg of ik tijd had', back: 'She asked if I had time' },
    {
      front: 'Hij vertelde dat hij was verhuisd',
      back: 'He said he had moved',
    },
    { front: 'de volgende dag', back: 'the next day (time shift)' },
    { front: 'Hij vroeg waar ik woonde', back: 'He asked where I lived' },
  ],
  'b1/11-te-plus-infinitive': [
    { front: 'Het is moeilijk te zeggen', back: 'It is hard to say' },
    { front: 'Ik kom om te helpen', back: 'I come to help' },
    { front: 'zonder te vragen', back: 'without asking' },
    { front: 'na te hebben gegeten', back: 'after having eaten' },
    { front: 'Ik probeer Nederlands te spreken', back: 'I try to speak Dutch' },
    { front: 'Leuk je te ontmoeten', back: 'Nice to meet you' },
  ],
  'b1/12-word-order-masterclass': [
    { front: 'Morgen ga ik werken', back: 'Tomorrow I go to work (inversion)' },
    {
      front: '… omdat ik morgen moet werken',
      back: '… because I have to work tomorrow (verb cluster)',
    },
    { front: 'Gisteren heb ik hem gezien', back: 'Yesterday I saw him' },
    {
      front: 'Ik ga morgen met de trein naar Utrecht',
      back: 'Time – Manner – Place example',
    },
    { front: 'Daarom blijf ik thuis', back: 'That is why I stay home' },
    {
      front: 'Ik blijf thuis, want ik ben moe',
      back: 'want keeps V2 (coordinate)',
    },
  ],
  'b1/13-nuanced-opinions': [
    { front: 'Naar mijn mening', back: 'In my opinion' },
    { front: 'Ik ben er niet zeker van dat …', back: 'I am not sure that …' },
    { front: 'Het lijkt me dat …', back: 'It seems to me that …' },
    { front: 'Ik twijfel of …', back: 'I doubt whether …' },
    { front: 'Voor zover ik weet', back: 'As far as I know' },
    { front: 'Ik ben bang dat …', back: 'I am afraid that …' },
  ],
  'b1/14-agreeing-and-debating': [
    { front: 'Daar ben ik het mee eens', back: 'I agree with that' },
    { front: 'Ik zie dat anders', back: 'I see it differently' },
    { front: 'Enerzijds … anderzijds', back: 'On one hand … on the other' },
    { front: 'Dat is een goed punt', back: 'That is a good point' },
    { front: 'Ik begrijp je punt', back: 'I understand your point' },
    {
      front: 'Daar ben ik het niet mee eens',
      back: 'I do not agree with that',
    },
  ],
  'b1/15-reading-the-news': [
    { front: 'volgens de bron', back: 'according to the source' },
    { front: 'het bericht meldt dat …', back: 'the report states that …' },
    {
      front: 'De regering kondigde aan dat …',
      back: 'The government announced that …',
    },
    { front: 'de kop', back: 'the headline' },
    { front: 'het artikel', back: 'the article' },
    { front: 'de bron', back: 'the source' },
  ],
  'b1/16-formal-letters-and-emails': [
    { front: 'Geachte heer/mevrouw', back: 'Dear Sir/Madam' },
    { front: 'Met vriendelijke groet', back: 'Kind regards' },
    {
      front: 'Hierbij informeer ik u dat …',
      back: 'I hereby inform you that …',
    },
    {
      front: 'In de bijlage vindt u …',
      back: 'In the attachment you will find …',
    },
    {
      front: 'Met deze e-mail reageer ik op …',
      back: 'With this email I respond to …',
    },
    {
      front: 'Ik hoor graag van u',
      back: 'I look forward to hearing from you',
    },
  ],
  'b1/17-work-meetings-and-applications': [
    { front: 'sollicitatiegesprek', back: 'job interview' },
    {
      front: 'Ik zou graag willen solliciteren',
      back: 'I would like to apply',
    },
    { front: 'Kunt u dat toelichten?', back: 'Can you elaborate on that?' },
    { front: 'de agenda', back: 'the agenda' },
    { front: 'de actiepunten', back: 'action points' },
    {
      front: 'Ik solliciteer op deze functie',
      back: 'I am applying for this position',
    },
  ],
  'b1/18-education-and-learning': [
    { front: 'inschrijven', back: 'enrol / register' },
    { front: 'het tentamen', back: 'the exam' },
    {
      front: 'Ik studeer … aan de universiteit',
      back: 'I study … at the university',
    },
    { front: 'de docent', back: 'lecturer' },
    { front: 'de student', back: 'student' },
    { front: 'Ik heb mijn examen gehaald', back: 'I passed my exam' },
  ],
  'b1/19-society-and-environment': [
    { front: 'de gemeente', back: 'municipality' },
    { front: 'duurzaamheid', back: 'sustainability' },
    { front: 'het zorgstelsel', back: 'healthcare system' },
    { front: 'de bijstand', back: 'social assistance' },
    { front: 'het milieu', back: 'the environment' },
    { front: 'de regering', back: 'the government' },
  ],
  'b1/20-feelings-and-relationships': [
    { front: 'Ik voel me …', back: 'I feel …' },
    { front: 'We hebben ruzie gehad', back: 'We had an argument' },
    { front: 'Ik vertrouw je', back: 'I trust you' },
    { front: 'Het spijt me dat …', back: 'I am sorry that …' },
    { front: 'Ik ben boos', back: 'I am angry' },
    { front: 'Ik mis je', back: 'I miss you' },
  ],
  'b1/21-dutch-culture-and-directness': [
    { front: 'Met alle respect, maar …', back: 'With all due respect, but …' },
    { front: 'gezellig', back: 'cosy / fun together' },
    { front: 'Zullen we iets afspreken?', back: 'Shall we plan something?' },
    {
      front: 'Nee, dat kan niet',
      back: 'No, that is not possible (direct but normal)',
    },
    { front: 'Geen probleem', back: 'No problem' },
    { front: 'Doe maar', back: 'Go ahead / never mind' },
  ],
  'b1/22-storytelling-past-tenses': [
    {
      front: 'Ik was net thuisgekomen toen …',
      back: 'I had just come home when …',
    },
    {
      front: 'Ik woonde in Amsterdam',
      back: 'I lived in Amsterdam (background)',
    },
    { front: 'Toen ben ik verhuisd', back: 'Then I moved (event)' },
    { front: 'Op een dag …', back: 'One day … (story opener)' },
    { front: 'Het was een drukke week', back: 'It was a busy week' },
    { front: 'Uiteindelijk …', back: 'In the end …' },
  ],
  'b1/23-diminutives': [
    { front: 'het kopje', back: 'the cup / cup of (coffee)' },
    { front: 'broodje', back: 'sandwich' },
    { front: 'even gezellig', back: 'a bit cosy (friendly tone)' },
    { front: 'het huisje', back: 'the little house' },
    { front: 'meisje', back: 'girl / little girl' },
    { front: 'autootje', back: 'little car (affectionate)' },
  ],
  'b1/24-particles-masterclass': [
    { front: 'Kom maar binnen', back: 'Come on in (welcoming)' },
    { front: 'Doe maar', back: 'Go ahead / never mind' },
    { front: 'Dat is toch logisch?', back: 'That is logical, right?' },
    { front: 'Kom gerust even langs', back: 'Feel free to drop by for a bit' },
    { front: 'Wacht even', back: 'Wait a moment' },
    { front: 'Dat is maar goed ook', back: 'That is just as well' },
  ],
  'b1/25-idioms-and-expressions': [
    { front: 'Het regent pijpenstelen', back: 'It is raining cats and dogs' },
    { front: 'Op de bonnefooi', back: 'On the spur of the moment' },
    { front: 'De kogel is door de kerk', back: 'The decision is made' },
    { front: 'Iets uit de losse pols', back: 'Something off the cuff' },
    { front: 'Dat valt wel mee', back: 'That is not so bad' },
    { front: 'Het komt goed', back: 'It will be fine' },
  ],
  'b1/26-fast-speech-strategies': [
    { front: 'Kunt u dat herhalen?', back: 'Can you repeat that?' },
    { front: 'Kunt u langzamer praten?', back: 'Can you speak more slowly?' },
    {
      front: 'Ik begrijp het woord … niet',
      back: 'I do not understand the word …',
    },
    { front: 'Wat bedoelt u?', back: 'What do you mean?' },
    {
      front: 'Even langzaam, alsjeblieft',
      back: 'Slowly for a moment, please',
    },
    { front: 'Kunt u dat uitleggen?', back: 'Can you explain that?' },
  ],
  'b1/27-practical-netherlands': [
    { front: 'inschrijven bij de gemeente', back: 'register at municipality' },
    { front: 'het BSN', back: 'citizen service number' },
    { front: 'de zorgverzekering', back: 'health insurance' },
    { front: 'DigiD', back: 'government login' },
    { front: 'de huisarts', back: 'GP / family doctor' },
    {
      front: 'Kunt u me helpen met inschrijven?',
      back: 'Can you help me register?',
    },
  ],
  'b1/28-bringing-it-together': [
    {
      front: 'Kunt u dat herhalen?',
      back: 'Can you repeat that? (recovery phrase)',
    },
    {
      front: 'Met vriendelijke groet',
      back: 'Kind regards (formal email close)',
    },
    { front: 'Ik zou graag …', back: 'I would like … (polite request)' },
    { front: 'Naar mijn mening', back: 'In my opinion' },
    {
      front: 'Het rapport is afgerond',
      back: 'The report is finished (passive state)',
    },
    { front: 'Geachte heer/mevrouw', back: 'Dear Sir/Madam (formal open)' },
  ],
};

export function getLessonFlashcards(lessonId: string): FlashcardItem[] {
  return LESSON_FLASHCARDS[lessonId] ?? [];
}
