export type FlashcardItem = {
  front: string;
  back: string;
  example?: string;
};

export const LESSON_FLASHCARDS: Record<string, FlashcardItem[]> = {
  'a0/01-greetings-and-introductions': [
    { front: 'Hoe heet je?', back: 'What is your name?' },
    { front: 'Goedemorgen', back: 'Good morning' },
    { front: 'Goedenavond', back: 'Good evening' },
    { front: 'Tot ziens', back: 'Goodbye (polite)' },
    { front: 'Aangenaam', back: 'Nice to meet you' },
    { front: 'Ik ben …', back: 'I am …' },
    { front: 'Hallo', back: 'Hello' },
    { front: 'Hoi', back: 'Hi' },
    { front: 'Goedemiddag', back: 'Good afternoon' },
    { front: 'Dag', back: 'Bye / Hello' },
    { front: 'Tot straks', back: 'See you soon' },
    { front: 'Prettig kennis te maken', back: 'Pleased to meet you' },
  ],
  'a0/02-alphabet-and-spelling': [
    { front: 'Hoe spel je dat?', back: 'How do you spell that?' },
    { front: 'Langzaam, alsjeblieft', back: 'Slowly, please' },
    { front: 'Ik begrijp het niet', back: 'I do not understand' },
    { front: 'Kunt u dat spellen?', back: 'Can you spell that?' },
    { front: 'de maan', back: 'the moon (long aa)' },
    { front: 'de man', back: 'the man (short a)' },
    { front: 'het alfabet', back: 'the alphabet' },
    { front: 'de letter', back: 'the letter' },
    { front: 'de klinker', back: 'the vowel' },
    { front: 'de hoofdletter', back: 'the capital letter' },
    { front: 'met dubbel a', back: 'with double a' },
    { front: 'Kunt u dat opschrijven?', back: 'Can you write that down?' },
  ],
  'a0/03-numbers-0-20-and-age': [
    { front: 'Hoe oud ben je?', back: 'How old are you?' },
    { front: 'Ik ben twintig jaar', back: 'I am twenty years old' },
    { front: 'vijftien', back: 'fifteen' },
    { front: 'nul', back: 'zero' },
    { front: 'dertien', back: 'thirteen' },
    { front: 'achttien', back: 'eighteen' },
    { front: 'één', back: 'one' },
    { front: 'tien', back: 'ten' },
    { front: 'twaalf', back: 'twelve' },
    { front: 'twintig', back: 'twenty' },
    { front: 'zeventien', back: 'seventeen' },
    { front: 'Hoeveel?', back: 'How many?' },
  ],
  'a0/04-pronouns-and-zijn': [
    { front: 'Hoe gaat het?', back: 'How are you? (How goes it?)' },
    { front: 'u / u bent', back: 'formal you / you are (formal)' },
    { front: 'wij zijn', back: 'we are' },
    { front: 'jij bent', back: 'you are (informal)' },
    { front: 'zij is', back: 'she is' },
    { front: 'zij zijn', back: 'they are' },
    { front: 'ik ben', back: 'I am' },
    { front: 'hij is', back: 'he is' },
    { front: 'het is', back: 'it is' },
    { front: 'jullie zijn', back: 'you (plural) are' },
    { front: 'Ben jij …?', back: 'Are you …?' },
    { front: 'wij', back: 'we' },
  ],
  'a0/05-hebben-and-everyday-things': [
    { front: 'Ik heb honger', back: 'I am hungry (lit. I have hunger)' },
    { front: 'Ik heb dorst', back: 'I am thirsty' },
    { front: 'Ik heb het koud', back: 'I am cold' },
    { front: 'Heb jij …?', back: 'Do you have …?' },
    { front: 'Ik heb een fiets', back: 'I have a bicycle' },
    { front: 'Ik heb geen tijd', back: 'I have no time' },
    { front: 'Ik heb het warm', back: 'I am warm' },
    { front: 'Ik heb een auto', back: 'I have a car' },
    { front: 'Ik heb een vraag', back: 'I have a question' },
    { front: 'Ik heb haast', back: "I'm in a hurry" },
    { front: 'Hij heeft …', back: 'He has …' },
    { front: 'Wij hebben …', back: 'We have …' },
  ],
  'a0/06-basic-questions': [
    { front: 'wie', back: 'who' },
    { front: 'wat', back: 'what' },
    { front: 'waar', back: 'where' },
    { front: 'wanneer', back: 'when' },
    { front: 'waarom', back: 'why' },
    { front: 'hoe', back: 'how' },
    { front: 'hoeveel', back: 'how much / many' },
    { front: 'welke', back: 'which' },
    { front: 'Wat is dat?', back: 'What is that?' },
    { front: 'Waar is …?', back: 'Where is …?' },
    { front: 'Waarom niet?', back: 'Why not?' },
    { front: 'Hoe laat?', back: 'What time?' },
  ],
  'a0/07-numbers-21-100-and-money': [
    { front: 'Hoeveel kost het?', back: 'How much does it cost?' },
    { front: 'vijfentwintig', back: 'twenty-five' },
    { front: 'tachtig', back: 'eighty' },
    { front: 'het geld', back: 'the money' },
    { front: 'euro', back: 'euro' },
    { front: 'tweehonderd', back: 'two hundred' },
    { front: 'honderd', back: 'hundred' },
    { front: 'vijftig', back: 'fifty' },
    { front: 'contant', back: 'cash' },
    { front: 'pinnen', back: 'to pay by card' },
    { front: 'Dat is drie euro', back: "That's three euros" },
    { front: 'het wisselgeld', back: 'the change' },
  ],
  'a0/08-days-months-and-dates': [
    { front: 'op maandag', back: 'on Monday' },
    { front: 'in mei', back: 'in May' },
    { front: 'het weekend', back: 'the weekend' },
    { front: 'vandaag', back: 'today' },
    { front: 'morgen', back: 'tomorrow' },
    { front: 'gisteren', back: 'yesterday' },
    { front: 'de dag', back: 'the day' },
    { front: 'de maand', back: 'the month' },
    { front: 'zaterdag', back: 'Saturday' },
    { front: 'zondag', back: 'Sunday' },
    { front: 'januari', back: 'January' },
    { front: 'Welke dag is het?', back: 'What day is it?' },
  ],
  'a0/09-where-do-you-live': [
    { front: 'Ik woon in …', back: 'I live in …' },
    { front: 'Ik kom uit …', back: 'I come from …' },
    { front: 'Waar woon je?', back: 'Where do you live?' },
    { front: 'de stad', back: 'the city' },
    { front: 'het dorp', back: 'the village' },
    { front: 'Nederland', back: 'the Netherlands' },
    { front: 'het adres', back: 'the address' },
    { front: 'de straat', back: 'the street' },
    { front: 'het land', back: 'the country' },
    { front: 'België', back: 'Belgium' },
    { front: 'de postcode', back: 'the postcode' },
    { front: 'Ik woon in een flat', back: 'I live in a flat' },
  ],
  'a0/10-ordering-food-and-drink': [
    { front: 'Ik wil graag …', back: 'I would like … (polite)' },
    { front: 'de rekening, alstublieft', back: 'the bill, please' },
    { front: 'het brood', back: 'the bread' },
    { front: 'de koffie', back: 'the coffee' },
    { front: 'het water', back: 'the water' },
    { front: 'Mag ik …?', back: 'May I have …?' },
    { front: 'de thee', back: 'the tea' },
    { front: 'het bier', back: 'the beer' },
    { front: 'een broodje', back: 'a sandwich' },
    { front: 'Alstublieft', back: 'Here you are / please' },
    { front: 'Smakelijk eten!', back: 'Enjoy your meal!' },
    { front: 'Ik wil graag afrekenen', back: "I'd like to pay" },
  ],
  'a0/11-telling-time-and-reading-the-clock': [
    { front: 'Hoe laat is het?', back: 'What time is it?' },
    { front: 'half zeven', back: '6:30 (Dutch half rule)' },
    { front: 'kwart over acht', back: 'quarter past eight' },
    { front: 'om acht uur', back: "at eight o'clock" },
    { front: 'te laat', back: 'late' },
    { front: 'op tijd', back: 'on time' },
    { front: 'kwart voor negen', back: 'quarter to nine' },
    { front: 'vijf over tien', back: 'five past ten' },
    { front: 'het is twaalf uur', back: "it's twelve o'clock" },
    { front: "'s ochtends", back: 'in the morning' },
    { front: "'s avonds", back: 'in the evening' },
    { front: 'het uur', back: 'the hour' },
  ],
  'a0/12-de-het-primer': [
    { front: 'het brood', back: 'the bread (het word)' },
    { front: 'de fiets', back: 'the bicycle (de word)' },
    { front: 'de koffie', back: 'the coffee' },
    { front: 'het water', back: 'the water' },
    { front: 'de taal', back: 'the language' },
    { front: 'het huis', back: 'the house' },
    { front: 'de auto', back: 'the car (de)' },
    { front: 'het boek', back: 'the book (het)' },
    { front: 'de tafel', back: 'the table (de)' },
    { front: 'het kind', back: 'the child (het)' },
    { front: 'de stoel', back: 'the chair (de)' },
    { front: 'het raam', back: 'the window (het)' },
  ],
  'a0/13-nationalities-and-languages': [
    { front: 'Ik ben Nederlander', back: 'I am Dutch (a Dutch man)' },
    { front: 'Ik ben Nederlandse', back: 'I am Dutch (a Dutch woman)' },
    {
      front: 'Ik spreek een beetje Nederlands',
      back: 'I speak a little Dutch',
    },
    { front: 'Welke talen spreek je?', back: 'Which languages do you speak?' },
    { front: 'de nationaliteit', back: 'the nationality' },
    { front: 'Ik leer Nederlands', back: 'I am learning Dutch' },
    { front: 'Engels', back: 'English' },
    { front: 'Duits', back: 'German' },
    { front: 'de taal', back: 'the language' },
    { front: 'Ik ben Belg', back: "I'm Belgian" },
    { front: 'Waar kom je vandaan?', back: 'Where are you from?' },
    { front: 'Ik spreek vloeiend Engels', back: 'I speak fluent English' },
  ],
  'a0/14-getting-by-survival-phrases': [
    { front: 'Ik begrijp het niet', back: 'I do not understand' },
    { front: 'Kunt u dat herhalen?', back: 'Can you repeat that?' },
    { front: 'Kunt u langzamer praten?', back: 'Can you speak more slowly?' },
    { front: 'Wat betekent dat?', back: 'What does that mean?' },
    {
      front: 'Hoe zeg je … in het Nederlands?',
      back: 'How do you say … in Dutch?',
    },
    { front: 'Spreekt u Engels?', back: 'Do you speak English?' },
    { front: 'Ik weet het niet', back: "I don't know" },
    { front: 'Een momentje', back: 'One moment' },
    { front: 'Sorry?', back: 'Sorry?' },
    { front: 'Nog een keer, alstublieft', back: 'Once more, please' },
    { front: 'Wat zei u?', back: 'What did you say?' },
    { front: 'Pardon', back: 'Excuse me' },
  ],
  'a1/01-daily-routines': [
    { front: 'Ik sta om zeven uur op', back: 'I get up at seven' },
    { front: 'Wat doe je vandaag?', back: 'What are you doing today?' },
    { front: 'altijd', back: 'always' },
    { front: 'meestal', back: 'usually' },
    { front: 'soms', back: 'sometimes' },
    { front: 'nooit', back: 'never' },
    { front: 'Ik werk van negen tot vijf', back: 'I work from nine to five' },
    { front: "'s ochtends", back: 'in the morning' },
    { front: 'Eerst … dan …', back: 'First … then …' },
    { front: 'Ik ga naar mijn werk', back: 'I go to work' },
    { front: 'elke dag', back: 'every day' },
    { front: 'Ik ga om elf uur slapen', back: 'I go to sleep at eleven' },
  ],
  'a1/02-word-order-svo': [
    { front: 'Vandaag werk ik thuis', back: 'Today I work at home (V2)' },
    { front: 'Werk jij vandaag?', back: 'Do you work today?' },
    { front: 'Morgen ga ik naar school', back: 'Tomorrow I go to school' },
    { front: 'Ik eet thuis', back: 'I eat at home' },
    { front: 'Waar woon je?', back: 'Where do you live?' },
    { front: 'niet', back: 'not' },
    { front: 'Ik drink koffie', back: 'I drink coffee' },
    { front: 'In het weekend sport ik', back: 'At the weekend I do sport' },
    { front: 'Waarom kom je niet?', back: "Why aren't you coming?" },
    { front: 'Hij woont in Utrecht', back: 'He lives in Utrecht' },
    { front: 'Wat eet je?', back: 'What do you eat?' },
    { front: 'Straks ga ik naar huis', back: "Later I'll go home" },
  ],
  'a1/03-negation': [
    { front: 'Ik heb geen tijd', back: 'I have no time' },
    { front: 'Ik werk niet', back: 'I do not work' },
    { front: 'Ik sta niet op', back: 'I do not get up' },
    { front: 'geen melk', back: 'no milk (indefinite noun)' },
    { front: 'niet vandaag', back: 'not today' },
    { front: 'Heb je geen honger?', back: 'Are you not hungry?' },
    { front: 'Ik heb geen geld', back: 'I have no money' },
    { front: 'Dat is niet goed', back: "That's not good" },
    { front: 'Ik ken hem niet', back: "I don't know him" },
    { front: 'geen probleem', back: 'no problem' },
    { front: 'niet meer', back: 'not anymore' },
    { front: 'nog niet', back: 'not yet' },
  ],
  'a1/04-family': [
    { front: 'de moeder', back: 'mother' },
    { front: 'de vader', back: 'father' },
    { front: 'Ik heb geen kinderen', back: 'I have no children' },
    { front: 'Dit is mijn zus', back: 'This is my sister' },
    { front: 'de broer', back: 'brother' },
    { front: 'de familie', back: 'the family' },
    { front: 'de ouders', back: 'the parents' },
    { front: 'de zoon', back: 'the son' },
    { front: 'de dochter', back: 'the daughter' },
    { front: 'de oma', back: 'the grandma' },
    { front: 'de opa', back: 'the grandpa' },
    { front: 'getrouwd', back: 'married' },
  ],
  'a1/05-possessives': [
    { front: 'mijn moeder', back: 'my mother' },
    { front: 'jouw fiets', back: 'your bicycle' },
    { front: 'zijn auto', back: 'his car' },
    { front: 'haar tas', back: 'her bag' },
    { front: 'ons huis', back: 'our house (het word)' },
    { front: 'onze fiets', back: 'our bicycle (de word)' },
    { front: 'hun huis', back: 'their house' },
    { front: 'jullie auto', back: 'your (plural) car' },
    { front: 'uw naam', back: 'your (formal) name' },
    { front: 'Is dit van jou?', back: 'Is this yours?' },
    { front: 'mijn familie', back: 'my family' },
    { front: 'onze buren', back: 'our neighbours' },
  ],
  'a1/06-food-and-drink': [
    { front: 'de melk', back: 'the milk' },
    { front: 'het brood', back: 'the bread' },
    { front: 'Ik wil graag …', back: 'I would like …' },
    { front: 'de appel', back: 'the apple' },
    { front: 'het fruit', back: 'the fruit' },
    { front: 'de kaas', back: 'the cheese' },
    { front: 'de groente', back: 'the vegetable(s)' },
    { front: 'het vlees', back: 'the meat' },
    { front: 'de vis', back: 'the fish' },
    { front: 'het ei', back: 'the egg' },
    { front: 'lekker', back: 'tasty' },
    { front: 'Ik heb honger', back: "I'm hungry" },
  ],
  'a1/07-at-the-restaurant': [
    { front: 'Mag ik de menukaart?', back: 'May I have the menu?' },
    { front: 'de rekening, alstublieft', back: 'the bill, please' },
    { front: 'Ik zou graag …', back: 'I would like … (polite)' },
    { front: 'Het smaakt goed', back: 'It tastes good' },
    { front: 'Nog iets te drinken?', back: 'Anything else to drink?' },
    { front: 'de ober / de serveerster', back: 'waiter / waitress' },
    { front: 'het voorgerecht', back: 'the starter' },
    { front: 'het hoofdgerecht', back: 'the main course' },
    { front: 'het toetje', back: 'the dessert' },
    { front: 'Voor mij graag …', back: 'For me, please …' },
    { front: 'het menu van de dag', back: 'the daily menu' },
    { front: 'Kan ik pinnen?', back: 'Can I pay by card?' },
  ],
  'a1/08-shopping': [
    { front: 'Hoeveel kost het?', back: 'How much does it cost?' },
    { front: 'Ik wil graag betalen', back: 'I would like to pay' },
    { front: 'deze jas', back: 'this coat' },
    { front: 'die schoenen', back: 'those shoes' },
    { front: 'Te duur', back: 'Too expensive' },
    { front: 'Hebt u maat M?', back: 'Do you have size M?' },
    { front: 'de winkel', back: 'the shop' },
    { front: 'goedkoop', back: 'cheap' },
    { front: 'de korting', back: 'the discount' },
    { front: 'in de aanbieding', back: 'on offer' },
    { front: 'Ik kijk alleen even', back: "I'm just looking" },
    { front: 'het pashokje', back: 'the fitting room' },
  ],
  'a1/09-demonstratives': [
    { front: 'deze tafel', back: 'this table (de word)' },
    { front: 'dit boek', back: 'this book (het word)' },
    { front: 'die jas', back: 'that coat' },
    { front: 'dat huis', back: 'that house' },
    { front: 'Is dit van jou?', back: 'Is this yours?' },
    { front: 'Welke wil je?', back: 'Which one do you want?' },
    { front: 'deze', back: 'this (de)' },
    { front: 'dit', back: 'this (het)' },
    { front: 'die', back: 'that (de)' },
    { front: 'dat', back: 'that (het)' },
    { front: 'deze hier', back: 'this one here' },
    { front: 'die daar', back: 'that one there' },
  ],
  'a1/10-plural-nouns': [
    { front: 'de boeken', back: 'the books' },
    { front: 'de kinderen', back: 'the children' },
    { front: "de auto's", back: 'the cars (+s plural)' },
    { front: 'de stoelen', back: 'the chairs (+en plural)' },
    { front: 'de eieren', back: 'the eggs' },
    { front: 'de fietsen', back: 'the bicycles' },
    { front: 'de huizen', back: 'the houses' },
    { front: 'de mannen', back: 'the men' },
    { front: 'de vrouwen', back: 'the women' },
    { front: 'de tafels', back: 'the tables' },
    { front: 'de dagen', back: 'the days' },
    { front: 'de steden', back: 'the cities' },
  ],
  'a1/11-adjectives': [
    { front: 'De stad is groot', back: 'The city is big (no -e after zijn)' },
    { front: 'de grote stad', back: 'the big city (-e with de)' },
    { front: 'het grote huis', back: 'the big house (-e with het + de adj)' },
    { front: 'een mooi huis', back: 'a beautiful house (indefinite het)' },
    { front: 'Het weer is slecht', back: 'The weather is bad' },
    { front: 'de kleine kamer', back: 'the small room' },
    { front: 'een oud huis', back: 'an old house' },
    { front: 'de nieuwe auto', back: 'the new car' },
    { front: 'een lekkere koffie', back: 'a nice coffee' },
    { front: 'het koude water', back: 'the cold water' },
    { front: 'een dure jas', back: 'an expensive coat' },
    { front: 'de rode fiets', back: 'the red bike' },
  ],
  'a1/12-more-present-verbs': [
    { front: 'Ik wil koffie drinken', back: 'I want to drink coffee' },
    { front: 'Ik kan niet komen', back: 'I cannot come' },
    { front: 'Ik moet werken', back: 'I have to work' },
    { front: 'Kun je me helpen?', back: 'Can you help me?' },
    { front: 'Ik mag niet roken', back: 'I am not allowed to smoke' },
    { front: 'Ik lees een boek', back: 'I read a book' },
    { front: 'Ik ga naar huis', back: "I'm going home" },
    { front: 'Ik kom uit Engeland', back: 'I come from England' },
    { front: 'Ik geef het je', back: "I'll give it to you" },
    { front: 'Ik neem de bus', back: 'I take the bus' },
    { front: 'Ik zie je morgen', back: 'See you tomorrow' },
    { front: 'Ik doe mijn best', back: 'I do my best' },
  ],
  'a1/13-housing': [
    { front: 'Ik woon in een flat', back: 'I live in a flat' },
    { front: 'de woonkamer', back: 'the living room' },
    { front: 'de slaapkamer', back: 'the bedroom' },
    { front: 'de keuken', back: 'the kitchen' },
    { front: 'Het boek ligt op de tafel', back: 'The book is on the table' },
    {
      front: 'De lamp hangt aan het plafond',
      back: 'The lamp hangs from the ceiling',
    },
    { front: 'de badkamer', back: 'the bathroom' },
    { front: 'de tuin', back: 'the garden' },
    { front: 'de huur', back: 'the rent' },
    { front: 'het appartement', back: 'the apartment' },
    { front: 'De sleutel zit in het slot', back: 'The key is in the lock' },
    { front: 'Ik zoek een woning', back: "I'm looking for a place to live" },
  ],
  'a1/14-hobbies': [
    { front: 'Ik hou van lezen', back: 'I like reading' },
    { front: 'In mijn vrije tijd …', back: 'In my free time …' },
    { front: 'Ik sport graag', back: 'I like to exercise' },
    { front: 'Ik luister naar muziek', back: 'I listen to music' },
    { front: 'Ik speel gitaar', back: 'I play guitar' },
    { front: 'Wat doe je graag?', back: 'What do you like to do?' },
    { front: 'Ik hou van koken', back: 'I love cooking' },
    { front: 'Ik ga graag naar de film', back: 'I like going to the cinema' },
    { front: 'de hobby', back: 'the hobby' },
    { front: 'Ik teken', back: 'I draw' },
    { front: 'Ik wandel graag', back: 'I like walking' },
    { front: 'samen', back: 'together' },
  ],
  'a1/15-transport': [
    {
      front: 'Hoe kom ik bij het station?',
      back: 'How do I get to the station?',
    },
    { front: 'links', back: 'left' },
    { front: 'rechts', back: 'right' },
    { front: 'rechtdoor', back: 'straight ahead' },
    { front: 'de trein', back: 'the train' },
    { front: 'de OV-chipkaart', back: 'the OV chip card (public transport)' },
    { front: 'de bus', back: 'the bus' },
    { front: 'de fiets', back: 'the bike' },
    { front: 'de auto', back: 'the car' },
    { front: 'het perron', back: 'the platform' },
    { front: 'overstappen', back: 'to change (trains)' },
    { front: 'Waar moet ik uitstappen?', back: 'Where do I get off?' },
  ],
  'a1/16-weather': [
    { front: 'Het regent', back: 'It is raining' },
    { front: 'Het is warm', back: 'It is warm' },
    { front: 'Het is koud', back: 'It is cold' },
    { front: 'Ik heb het warm', back: 'I am warm (lit. I have it warm)' },
    { front: 'Het waait', back: 'It is windy' },
    { front: 'Het is zonnig', back: 'It is sunny' },
    { front: 'Het sneeuwt', back: "It's snowing" },
    { front: 'de zon', back: 'the sun' },
    { front: 'de wolk', back: 'the cloud' },
    { front: 'Het is bewolkt', back: "It's cloudy" },
    { front: 'de lente', back: 'spring' },
    { front: 'de winter', back: 'winter' },
  ],
  'a1/17-body-health': [
    { front: 'Ik ben ziek', back: 'I am ill' },
    { front: 'Ik heb hoofdpijn', back: 'I have a headache' },
    { front: 'de dokter', back: 'doctor' },
    { front: 'de apotheek', back: 'pharmacy' },
    { front: 'Ik voel me niet goed', back: 'I do not feel well' },
    { front: 'Waar doet het pijn?', back: 'Where does it hurt?' },
    { front: 'de keel', back: 'the throat' },
    { front: 'de buik', back: 'the belly' },
    { front: 'koorts', back: 'fever' },
    {
      front: 'Ik heb een afspraak bij de huisarts',
      back: 'I have a GP appointment',
    },
    { front: 'het medicijn', back: 'the medicine' },
    { front: 'verkouden', back: 'having a cold' },
  ],
  'a1/18-simple-past-regular': [
    { front: 'ik werkte', back: 'I worked (regular past)' },
    { front: 'Gisteren werkte ik thuis', back: 'Yesterday I worked at home' },
    { front: 'ik woonde', back: 'I lived' },
    { front: 'ik speelde', back: 'I played' },
    { front: 'ik luisterde', back: 'I listened' },
    { front: 'ik maakte', back: 'I made' },
    { front: 'ik kookte', back: 'I cooked' },
    { front: 'ik leerde', back: 'I learned' },
    { front: 'wij werkten', back: 'we worked' },
    { front: 'ik betaalde', back: 'I paid' },
    { front: 'ik fietste', back: 'I cycled' },
    { front: 'ik antwoordde', back: 'I answered' },
  ],
  'a1/19-simple-past-irregular': [
    { front: 'Ik ging naar huis', back: 'I went home' },
    { front: 'Ik kwam laat', back: 'I came late' },
    { front: 'Ik had geen tijd', back: 'I had no time' },
    { front: 'Ik was moe', back: 'I was tired' },
    { front: 'Ik zag hem gisteren', back: 'I saw him yesterday' },
    { front: 'Hij zei nee', back: 'He said no' },
    { front: 'Ik at een broodje', back: 'I ate a sandwich' },
    { front: 'Ik dronk koffie', back: 'I drank coffee' },
    { front: 'Ik deed het', back: 'I did it' },
    { front: 'Ik nam de trein', back: 'I took the train' },
    { front: 'Wij waren thuis', back: 'We were home' },
    { front: 'Hij gaf mij een cadeau', back: 'He gave me a gift' },
  ],
  'a1/20-reflexive-verbs': [
    { front: 'Ik was me', back: 'I wash myself / I shower' },
    { front: 'Ik kleed me aan', back: 'I get dressed' },
    { front: 'Ik scheren me', back: 'I shave' },
    { front: 'Ik voel me goed', back: 'I feel good' },
    { front: 'Hij scheert zich', back: 'He shaves (formal/reflexive)' },
    { front: 'Wij wassen ons', back: 'We wash ourselves' },
    { front: 'Ik haast me', back: 'I hurry' },
    { front: 'Ik verheug me op …', back: 'I look forward to …' },
    { front: 'Ik vergis me', back: "I'm mistaken" },
    { front: 'Jij voelt je moe', back: 'You feel tired' },
    { front: 'Zij kleedt zich aan', back: 'She gets dressed' },
    { front: 'Ik herinner me', back: 'I remember' },
  ],
  'a1/21-separable-verbs': [
    { front: 'Ik sta om zeven uur op', back: 'I get up at seven (op at end)' },
    { front: 'Ik bel je morgen op', back: 'I will call you tomorrow' },
    { front: 'Ik wil niet opstaan', back: 'I do not want to get up' },
    { front: 'uitgaan', back: 'to go out' },
    { front: 'meekomen', back: 'to come along' },
    { front: 'aankomen', back: 'to arrive' },
    { front: 'Ik ruim mijn kamer op', back: 'I tidy my room' },
    { front: 'Ik trek mijn jas aan', back: 'I put on my coat' },
    { front: 'Ik doe het licht uit', back: 'I turn off the light' },
    { front: 'Kom je mee?', back: 'Are you coming along?' },
    { front: 'De trein komt aan', back: 'The train arrives' },
    { front: 'Ik neem het mee', back: 'I take it with me' },
  ],
  'a1/22-clothing-and-colours': [
    { front: 'Ik draag een blauwe jas', back: 'I am wearing a blue coat' },
    { front: 'de broek', back: 'the trousers (singular in Dutch)' },
    { front: 'Welke maat heeft u?', back: 'What size do you take?' },
    { front: 'Kan ik dit passen?', back: 'Can I try this on?' },
    { front: 'een rode trui', back: 'a red sweater' },
    { front: 'de kleding', back: 'the clothing' },
    { front: 'de schoenen', back: 'the shoes' },
    { front: 'het overhemd', back: 'the shirt' },
    { front: 'de jurk', back: 'the dress' },
    { front: 'groen', back: 'green' },
    { front: 'zwart', back: 'black' },
    { front: 'wit', back: 'white' },
  ],
  'a1/23-asking-and-giving-directions': [
    {
      front: 'Hoe kom ik bij het station?',
      back: 'How do I get to the station?',
    },
    { front: 'Ga rechtdoor', back: 'Go straight ahead' },
    { front: 'Sla linksaf', back: 'Turn left' },
    { front: 'Steek de straat over', back: 'Cross the street' },
    { front: 'Ik ben de weg kwijt', back: 'I am lost' },
    { front: 'Is het ver?', back: 'Is it far?' },
    { front: 'bij het stoplicht', back: 'at the traffic light' },
    { front: 'op de hoek', back: 'on the corner' },
    { front: 'naast de bank', back: 'next to the bank' },
    { front: 'tegenover de kerk', back: 'opposite the church' },
    { front: 'de eerste straat rechts', back: 'the first street on the right' },
    {
      front: 'Kunt u het op de kaart laten zien?',
      back: 'Can you show it on the map?',
    },
  ],
  'a1/24-making-plans-and-suggestions': [
    { front: 'Zullen we koffie drinken?', back: 'Shall we drink coffee?' },
    {
      front: 'Heb je zin om mee te gaan?',
      back: 'Do you feel like coming along?',
    },
    { front: 'Laten we gaan!', back: "Let's go!" },
    { front: 'Ga je mee?', back: 'Are you coming along?' },
    { front: 'Hoe laat spreken we af?', back: 'What time shall we meet?' },
    { front: 'Ja, gezellig!', back: 'Yes, lovely!' },
    { front: 'Heb je zin in pizza?', back: 'Do you fancy pizza?' },
    { front: 'Zal ik koken?', back: 'Shall I cook?' },
    { front: 'Misschien een andere keer', back: 'Maybe another time' },
    { front: 'Waar spreken we af?', back: 'Where shall we meet?' },
    { front: 'Ik heb al een afspraak', back: 'I already have plans' },
    { front: 'Goed idee!', back: 'Good idea!' },
  ],
  'a2/01-past-tense-depth': [
    { front: 'Ik werkte gisteren', back: 'I worked yesterday' },
    {
      front: 'Toen woonde ik in Utrecht',
      back: 'Back then I lived in Utrecht',
    },
    { front: 'Vertel eens!', back: 'Tell me! (story prompt)' },
    { front: 'Ik luisterde naar muziek', back: 'I listened to music' },
    { front: 'Wij speelden voetbal', back: 'We played football' },
    { front: 'Het regende de hele dag', back: 'It rained all day' },
    { front: 'Vroeger woonde ik hier', back: 'I used to live here' },
    { front: 'Hij lachte hard', back: 'He laughed loudly' },
    { front: 'Ik dacht van wel', back: 'I thought so' },
    { front: 'Wij hadden geen tijd', back: 'We had no time' },
    { front: 'Zij kwamen te laat', back: 'They arrived late' },
    { front: 'Het was een mooie dag', back: 'It was a beautiful day' },
  ],
  'a2/02-perfect-tense-intro': [
    { front: 'Ik heb gewerkt', back: 'I have worked / I worked (spoken)' },
    { front: 'Ik ben gegaan', back: 'I went (zijn + movement)' },
    { front: 'Ik heb gegeten', back: 'I have eaten' },
    { front: 'Ben je klaar?', back: 'Are you ready?' },
    { front: 'Wij zijn thuisgekomen', back: 'We have come home' },
    { front: 'Ik heb het boek gelezen', back: 'I have read the book' },
    { front: 'Ik heb gedronken', back: 'I have drunk' },
    { front: 'Wat heb je gedaan?', back: 'What have you done?' },
    { front: 'Ik ben gevallen', back: 'I have fallen' },
    { front: 'Zij is vertrokken', back: 'She has left' },
    { front: 'Heb je goed geslapen?', back: 'Did you sleep well?' },
    { front: 'Ik heb hard gewerkt', back: "I've worked hard" },
  ],
  'a2/03-perfect-irregular': [
    { front: 'gegaan', back: 'gone (participle)' },
    { front: 'gezien', back: 'seen (participle)' },
    { front: 'gehad', back: 'had (participle)' },
    { front: 'Ik ben gegaan', back: 'I went' },
    { front: 'Ik heb gekocht', back: 'I have bought' },
    { front: 'Ik heb geschreven', back: 'I have written' },
    { front: 'gedronken', back: 'drunk' },
    { front: 'gegeten', back: 'eaten' },
    { front: 'genomen', back: 'taken' },
    { front: 'gegeven', back: 'given' },
    { front: 'gebleven', back: 'stayed' },
    { front: 'gekregen', back: 'received' },
  ],
  'a2/04-modals-in-depth': [
    { front: 'Ik moet morgen werken', back: 'I have to work tomorrow' },
    { front: 'Dat mag niet', back: 'That is not allowed' },
    { front: 'Zullen we afspreken?', back: 'Shall we meet?' },
    {
      front: 'Ik heb moeten werken',
      back: 'I had to work (double infinitive)',
    },
    { front: 'Mag ik hier zitten?', back: 'May I sit here?' },
    { front: 'Ik zou graag willen', back: 'I would like to (polite preview)' },
    { front: 'Ik kan zwemmen', back: 'I can swim' },
    { front: 'Je moet het doen', back: 'You have to do it' },
    { front: 'Mag ik iets vragen?', back: 'May I ask something?' },
    { front: 'Ik wil graag meer weten', back: "I'd like to know more" },
    { front: 'Kun je dat uitleggen?', back: 'Can you explain that?' },
    { front: 'We zouden kunnen gaan', back: 'We could go' },
  ],
  'a2/05-opinions': [
    { front: 'Ik vind dat …', back: 'I think that …' },
    { front: 'Volgens mij', back: 'In my opinion' },
    { front: 'Ik ben het eens met', back: 'I agree with' },
    { front: 'Ik ben het niet eens', back: 'I disagree' },
    { front: 'Dat klopt', back: 'That is correct' },
    { front: 'Ik denk van wel', back: 'I think so' },
    { front: 'Ik denk dat …', back: 'I think that …' },
    { front: 'Wat vind jij?', back: 'What do you think?' },
    { front: 'Naar mijn idee', back: 'In my view' },
    { front: 'Dat is waar', back: "That's true" },
    { front: 'Ik ben bang van niet', back: "I'm afraid not" },
    { front: 'Precies!', back: 'Exactly!' },
  ],
  'a2/06-comparatives': [
    { front: 'groter', back: 'bigger' },
    { front: 'beter', back: 'better (irregular)' },
    { front: 'meer … dan', back: 'more … than' },
    { front: 'minder … dan', back: 'less … than' },
    {
      front: 'Amsterdam is groter dan Utrecht',
      back: 'Amsterdam is bigger than Utrecht',
    },
    { front: 'Dit is beter', back: 'This is better' },
    { front: 'kleiner', back: 'smaller' },
    { front: 'ouder dan', back: 'older than' },
    { front: 'net zo groot als', back: 'as big as' },
    { front: 'duurder', back: 'more expensive' },
    { front: 'sneller', back: 'faster' },
    { front: 'even duur', back: 'equally expensive' },
  ],
  'a2/07-superlatives': [
    { front: 'het grootst', back: 'the biggest' },
    { front: 'het best', back: 'the best (irregular)' },
    { front: 'de meest interessante', back: 'the most interesting' },
    { front: 'Het mooiste is …', back: 'The best part is …' },
    { front: 'de kleinste', back: 'the smallest' },
    { front: 'de minst duur', back: 'the least expensive' },
    { front: 'het snelst', back: 'the fastest' },
    { front: 'de oudste', back: 'the oldest' },
    { front: 'het lekkerst', back: 'the tastiest' },
    { front: 'de beste film', back: 'the best film' },
    { front: 'het belangrijkst', back: 'the most important' },
    { front: 'op zijn best', back: 'at best' },
  ],
  'a2/08-describing-people': [
    { front: 'Hij is lang', back: 'He is tall' },
    { front: 'Ze heeft blauwe ogen', back: 'She has blue eyes' },
    { front: 'vriendelijk', back: 'friendly' },
    { front: 'serieus', back: 'serious' },
    { front: 'Hij heeft blond haar', back: 'He has blond hair' },
    { front: 'Ze is aardig', back: 'She is nice' },
    { front: 'Hij is klein', back: 'He is short' },
    { front: 'kort haar', back: 'short hair' },
    { front: 'Ze draagt een bril', back: 'She wears glasses' },
    { front: 'grappig', back: 'funny' },
    { front: 'verlegen', back: 'shy' },
    { front: 'Hij lijkt op zijn vader', back: 'He looks like his father' },
  ],
  'a2/09-describing-places': [
    { front: 'Het is druk', back: 'It is busy' },
    { front: 'Het is rustig', back: 'It is quiet' },
    { front: 'in het centrum', back: 'in the city centre' },
    { front: 'Er zijn veel cafés', back: 'There are many cafés' },
    { front: 'De stad is mooi', back: 'The city is beautiful' },
    { front: 'Het park is groot', back: 'The park is big' },
    { front: 'gezellig', back: 'cosy' },
    { front: 'het uitzicht', back: 'the view' },
    { front: 'in de buurt', back: 'nearby' },
    { front: 'Er is veel te doen', back: "There's a lot to do" },
    { front: 'het plein', back: 'the square' },
    { front: 'modern', back: 'modern' },
  ],
  'a2/10-prepositions-place': [
    { front: 'op de tafel', back: 'on the table' },
    { front: 'in de kamer', back: 'in the room' },
    { front: 'aan de deur', back: 'on/at the door' },
    { front: 'bij de ingang', back: 'at the entrance' },
    { front: 'naast de bank', back: 'next to the sofa' },
    { front: 'tegenover het station', back: 'opposite the station' },
    { front: 'onder de tafel', back: 'under the table' },
    { front: 'boven de kast', back: 'above the cupboard' },
    { front: 'tussen de huizen', back: 'between the houses' },
    { front: 'achter het huis', back: 'behind the house' },
    { front: 'voor de deur', back: 'in front of the door' },
    { front: 'in het midden', back: 'in the middle' },
  ],
  'a2/11-prepositions-time': [
    { front: 'op maandag', back: 'on Monday' },
    { front: 'in mei', back: 'in May' },
    { front: 'van … tot …', back: 'from … to …' },
    { front: 'sinds gisteren', back: 'since yesterday' },
    { front: 'om acht uur', back: "at eight o'clock" },
    { front: 'voor het eten', back: 'before dinner' },
    { front: 'na het werk', back: 'after work' },
    { front: 'tijdens de les', back: 'during the lesson' },
    { front: 'over een week', back: 'in a week' },
    { front: 'tot morgen', back: 'until tomorrow' },
    { front: 'binnen een uur', back: 'within an hour' },
    { front: 'rond zeven uur', back: 'around seven' },
  ],
  'a2/12-relative-clauses': [
    { front: 'de man die …', back: 'the man who …' },
    { front: 'het boek dat …', back: 'the book that … (het → dat)' },
    { front: 'de vrouw die ik ken', back: 'the woman I know' },
    { front: 'het huis dat we kopen', back: 'the house we are buying' },
    {
      front: 'Mijn broer, die in Groningen woont, …',
      back: 'My brother, who lives in Groningen, …',
    },
    { front: 'alles wat', back: 'everything that' },
    { front: 'de mensen die …', back: 'the people who …' },
    { front: 'het kind dat speelt', back: 'the child who plays' },
    { front: 'de film die ik zag', back: 'the film I saw' },
    { front: 'de stad waar ik woon', back: 'the city where I live' },
    { front: 'iets wat ik niet weet', back: "something I don't know" },
    { front: 'de auto die kapot is', back: "the car that's broken" },
  ],
  'a2/13-om-te': [
    {
      front: 'Ik leer om Nederlands te praten',
      back: 'I learn in order to speak Dutch',
    },
    { front: 'Ik kom om te helpen', back: 'I come to help' },
    { front: 'om … te …', back: 'in order to …' },
    { front: 'Ik werk om geld te verdienen', back: 'I work to earn money' },
    { front: 'Hij studeert om te slagen', back: 'He studies in order to pass' },
    { front: 'Wij reizen om te leren', back: 'We travel to learn' },
    {
      front: 'Ik bel om een afspraak te maken',
      back: "I'm calling to make an appointment",
    },
    { front: 'Ik heb geen tijd om te koken', back: 'I have no time to cook' },
    { front: 'Het is leuk om te doen', back: "It's fun to do" },
    { front: 'Ik ga om te winkelen', back: "I'm going shopping" },
    { front: 'genoeg om te eten', back: 'enough to eat' },
    { front: 'te moe om te werken', back: 'too tired to work' },
  ],
  'a2/14-subordinate-want-omdat': [
    {
      front: 'Ik blijf thuis omdat ik ziek ben',
      back: 'I stay home because I am ill',
    },
    {
      front: 'Ik eet thuis, want ik heb geen tijd',
      back: 'I eat at home, for I have no time',
    },
    { front: 'omdat …', back: 'because (verb at end)' },
    { front: 'want …', back: 'for / because (keeps V2)' },
    {
      front: 'Ik ga niet, omdat ik moe ben',
      back: 'I am not going because I am tired',
    },
    {
      front: 'Hij komt niet, want hij is ziek',
      back: 'He is not coming, for he is ill',
    },
    {
      front: 'Ik leer Nederlands omdat ik hier woon',
      back: 'I learn Dutch because I live here',
    },
    {
      front: 'Ze is blij omdat ze geslaagd is',
      back: "She's happy because she passed",
    },
    { front: 'want het regent', back: "because it's raining" },
    { front: 'de reden waarom', back: 'the reason why' },
    { front: 'omdat het moet', back: "because it's necessary" },
    {
      front: 'Hij blijft thuis omdat het regent',
      back: 'He stays home because it rains',
    },
  ],
  'a2/15-indirect-objects': [
    { front: 'Ik geef hem het boek', back: 'I give him the book' },
    { front: 'Geef me het', back: 'Give it to me' },
    { front: 'Leg het me uit', back: 'Explain it to me' },
    { front: 'Ik bel je morgen', back: 'I will call you tomorrow' },
    { front: 'Kun je me helpen?', back: 'Can you help me?' },
    { front: 'Ik stuur haar een e-mail', back: 'I send her an email' },
    { front: 'Ik geef het aan hem', back: 'I give it to him' },
    { front: 'Vertel me erover', back: 'Tell me about it' },
    { front: 'Ik laat het je zien', back: "I'll show it to you" },
    { front: 'Zij geeft ons les', back: 'She teaches us' },
    { front: 'Kun je het voor me doen?', back: 'Can you do it for me?' },
    { front: 'Ik breng je een cadeau', back: "I'll bring you a gift" },
  ],
  'a2/16-er-constructions': [
    { front: 'Er zijn veel mensen', back: 'There are many people' },
    { front: 'Er is geen tijd', back: 'There is no time' },
    { front: 'Is er een museum?', back: 'Is there a museum?' },
    { front: 'Ik heb er drie', back: 'I have three (of them)' },
    { front: 'Waar praat je over?', back: 'What are you talking about?' },
    { front: 'Daar praat ik over', back: 'That is what I am talking about' },
    { front: 'Er staat iemand voor de deur', back: "Someone's at the door" },
    { front: 'Er wordt gebeld', back: "The doorbell's ringing" },
    { front: 'Hoeveel heb je er?', back: 'How many do you have?' },
    { front: 'Er is niets aan de hand', back: "Nothing's wrong" },
    { front: 'Ik denk er niet aan', back: "I'm not thinking about it" },
    { front: 'Er zit iets in', back: "There's something in it" },
  ],
  'a2/17-workplace': [
    { front: 'de vergadering', back: 'the meeting' },
    { front: 'Ik heb een deadline', back: 'I have a deadline' },
    { front: 'thuiswerken', back: 'work from home' },
    { front: 'de baas', back: 'the boss' },
    { front: 'Ik ben op kantoor', back: 'I am at the office' },
    { front: 'Ik heb een drukke week', back: 'I have a busy week' },
    { front: 'de collega', back: 'the colleague' },
    { front: 'het salaris', back: 'the salary' },
    { front: 'de sollicitatie', back: 'the job application' },
    { front: 'de afspraak', back: 'the appointment' },
    { front: 'overwerken', back: 'to work overtime' },
    { front: 'het project', back: 'the project' },
  ],
  'a2/18-culture-traditions': [
    { front: 'Koningsdag', back: "King's Day (27 April)" },
    { front: 'Sinterklaas', back: '5 December tradition' },
    { front: 'gezellig', back: 'cosy / fun together' },
    { front: 'de oliebol', back: 'Dutch doughnut (New Year)' },
    { front: 'Het is feest', back: 'It is a celebration' },
    { front: 'Proost!', back: 'Cheers!' },
    { front: 'Oud en Nieuw', back: "New Year's Eve" },
    { front: 'het vuurwerk', back: 'the fireworks' },
    { front: 'Pasen', back: 'Easter' },
    { front: 'de verjaardag', back: 'the birthday' },
    { front: 'Gefeliciteerd!', back: 'Congratulations!' },
    { front: 'de tulp', back: 'the tulip' },
  ],
  'a2/19-appointments': [
    { front: 'afspraak maken', back: 'make an appointment' },
    { front: 'afspraak verzetten', back: 'reschedule an appointment' },
    { front: 'Heeft u tijd op …?', back: 'Do you have time on …?' },
    { front: 'Ik kan niet komen', back: 'I cannot come' },
    { front: 'Wanneer past het u?', back: 'When suits you?' },
    { front: 'Ik bevestig de afspraak', back: 'I confirm the appointment' },
    { front: 'afspraak afzeggen', back: 'to cancel an appointment' },
    {
      front: 'Ik wil een afspraak maken',
      back: "I'd like to make an appointment",
    },
    { front: 'Past woensdag u?', back: 'Does Wednesday suit you?' },
    { front: 'Ik ben verhinderd', back: "I'm unavailable" },
    { front: 'Tot dan!', back: 'See you then!' },
    { front: 'het spreekuur', back: 'the consultation hour' },
  ],
  'a2/20-conditional-als': [
    {
      front: 'Als ik tijd heb, bel ik je',
      back: 'If I have time, I will call you',
    },
    {
      front: 'Als het regent, blijf ik thuis',
      back: 'If it rains, I stay home',
    },
    { front: 'Als je hulp nodig hebt, …', back: 'If you need help, …' },
    {
      front: 'Als het morgen mooi is, …',
      back: 'If the weather is nice tomorrow, …',
    },
    { front: 'Als ik kan, kom ik', back: 'If I can, I will come' },
    { front: 'tenzij', back: 'unless' },
    {
      front: 'Als je wilt, kun je meekomen',
      back: 'If you want, you can come along',
    },
    { front: 'Als ik jou was, …', back: 'If I were you, …' },
    { front: 'Bel me als je er bent', back: "Call me when you're there" },
    {
      front: 'Wat doe je als het regent?',
      back: 'What do you do if it rains?',
    },
    { front: 'Als dat zo is, …', back: "If that's so, …" },
    { front: 'alleen als', back: 'only if' },
  ],
  'a2/21-passive-intro': [
    { front: 'Het huis wordt gebouwd', back: 'The house is being built' },
    { front: 'Er wordt gewerkt', back: 'Work is being done' },
    { front: 'De deur wordt geopend', back: 'The door is being opened' },
    {
      front: 'Het wordt morgen afgerond',
      back: 'It will be finished tomorrow',
    },
    { front: 'De taart wordt gemaakt', back: 'The cake is being made' },
    {
      front: 'Er wordt veel gepraat',
      back: 'There is a lot of talking going on',
    },
    { front: 'De brief wordt geschreven', back: 'The letter is being written' },
    {
      front: 'De kamer wordt schoongemaakt',
      back: 'The room is being cleaned',
    },
    { front: 'Het wordt verkocht', back: "It's being sold" },
    {
      front: 'De vergadering wordt verplaatst',
      back: 'The meeting is being moved',
    },
    { front: 'Er wordt niet gerookt', back: 'No smoking' },
    { front: 'De winkel wordt geopend', back: 'The shop is being opened' },
  ],
  'a2/22-present-continuous-aan-het': [
    { front: 'Ik ben aan het koken', back: 'I am cooking (right now)' },
    { front: 'Wat ben je aan het doen?', back: 'What are you doing?' },
    { front: 'Ik ben een boek aan het lezen', back: 'I am reading a book' },
    { front: 'Ik was aan het werken', back: 'I was working' },
    { front: 'Zij is het eten aan het koken', back: 'She is cooking the food' },
    {
      front: 'Ik werk elke dag',
      back: 'I work every day (habit → simple present)',
    },
    { front: 'We zijn aan het eten', back: "We're eating" },
    { front: 'Hij is aan het slapen', back: "He's sleeping" },
    { front: 'Ik ben aan het opruimen', back: "I'm tidying up" },
    { front: 'De kinderen zijn aan het spelen', back: 'The kids are playing' },
    { front: 'Ik was aan het bellen', back: 'I was on the phone' },
    { front: 'Ben je nog aan het werken?', back: 'Are you still working?' },
  ],
  'a2/23-telephone-calls': [
    { front: 'Met Anna', back: 'Anna speaking (answering the phone)' },
    { front: 'U spreekt met …', back: "You've reached … / this is …" },
    { front: 'Ik verbind u door', back: "I'll put you through" },
    { front: 'Kan hij mij terugbellen?', back: 'Can he call me back?' },
    { front: 'Zij is in gesprek', back: 'She is on another call' },
    { front: 'Sorry, verkeerd verbonden', back: 'Sorry, wrong number' },
    { front: 'Kunt u mij doorverbinden?', back: 'Can you put me through?' },
    { front: 'Blijft u aan de lijn', back: 'Please hold' },
    { front: 'Ik bel over …', back: "I'm calling about …" },
    {
      front: 'Wilt u een boodschap achterlaten?',
      back: 'Would you like to leave a message?',
    },
    { front: 'U valt weg', back: "You're breaking up" },
    { front: 'Bedankt voor het bellen', back: 'Thanks for calling' },
  ],
  'b1/01-conjunctions-overview': [
    { front: 'hoewel ik moe ben', back: 'although I am tired (verb last)' },
    { front: 'terwijl ik kook', back: 'while I cook' },
    { front: 'nadat we hebben gegeten', back: 'after we have eaten' },
    { front: 'voordat hij komt', back: 'before he comes' },
    { front: 'totdat ik klaar ben', back: 'until I am ready' },
    { front: 'tenzij het regent', back: 'unless it rains' },
    { front: 'zodat iedereen het snapt', back: 'so that everyone understands' },
    { front: 'zodra ik klaar ben', back: "as soon as I'm done" },
    { front: 'sinds ik hier woon', back: "since I've lived here" },
    { front: 'behalve als', back: 'except if' },
    { front: 'enerzijds … anderzijds', back: 'on one hand … on the other' },
    { front: 'ondanks dat', back: 'despite the fact that' },
  ],
  'b1/02-relative-clauses': [
    { front: 'de man wiens auto …', back: 'the man whose car …' },
    {
      front: 'het boek waarvan ik het begin',
      back: 'the book of which I know the beginning',
    },
    { front: 'waarmee', back: 'with which' },
    { front: 'de collega met wie ik werk', back: 'the colleague I work with' },
    { front: 'alles wat je zegt', back: 'everything you say' },
    { front: 'de stad waar ik woon', back: 'the city where I live' },
    { front: 'degene die …', back: 'the one who …' },
    { front: 'datgene wat …', back: 'that which …' },
    { front: 'het huis waarin ik woon', back: 'the house I live in' },
    { front: 'de reden waarom', back: 'the reason why' },
    { front: 'de vrouw wier …', back: 'the woman whose …' },
    { front: 'iets waar ik van hou', back: 'something I love' },
  ],
  'b1/03-waar-plus-preposition': [
    {
      front: 'Het punt waarover we praten',
      back: 'The point we are talking about',
    },
    { front: 'waarover', back: 'about which' },
    { front: 'waarin', back: 'in which' },
    { front: 'waarnaar', back: 'to which' },
    { front: 'de reden waarom', back: 'the reason why' },
    { front: 'de persoon van wie', back: 'the person from whom' },
    { front: 'waarmee', back: 'with which' },
    { front: 'waarop', back: 'on which' },
    { front: 'waaraan', back: 'to / on which' },
    { front: 'waarvoor', back: 'for which' },
    { front: 'Waar heb je het over?', back: 'What are you talking about?' },
    { front: 'Waar denk je aan?', back: 'What are you thinking about?' },
  ],
  'b1/04-future-with-zullen': [
    { front: 'Ik zal je morgen bellen', back: 'I will call you tomorrow' },
    { front: 'Zullen we afspreken?', back: 'Shall we meet?' },
    {
      front: 'Ik ga morgen werken',
      back: 'I am going to work tomorrow (spoken default)',
    },
    {
      front: 'De trein vertrekt om acht uur',
      back: 'The train leaves at eight (present for schedule)',
    },
    { front: 'Zal ik de deur openen?', back: 'Shall I open the door?' },
    { front: 'Wij zullen zien', back: 'We shall see' },
    { front: 'Het zal wel lukken', back: "It'll work out" },
    { front: 'Ik ga het proberen', back: "I'm going to try" },
    {
      front: 'Morgen wordt het mooi weer',
      back: 'Tomorrow the weather will be nice',
    },
    { front: 'Straks ga ik koken', back: "I'll cook later" },
    { front: 'Dat zal wel', back: 'I suppose so' },
    { front: 'We gaan verhuizen', back: "We're going to move" },
  ],
  'b1/05-zou-politeness-and-advice': [
    { front: 'Zou je me kunnen helpen?', back: 'Could you help me? (polite)' },
    { front: 'Ik zou wachten', back: 'I would wait (soft advice)' },
    {
      front: 'Zou u dat kunnen uitleggen?',
      back: 'Could you explain that? (formal)',
    },
    { front: 'Ik zou graag een koffie', back: 'I would like a coffee' },
    { front: 'Dat zou kunnen', back: 'That could be' },
    {
      front: 'Zou je even kunnen komen?',
      back: 'Could you come for a moment?',
    },
    { front: 'Ik zou maar oppassen', back: "I'd be careful" },
    { front: 'Je zou eens moeten rusten', back: 'You should get some rest' },
    { front: 'Zou het kunnen dat …?', back: 'Could it be that …?' },
    { front: 'Ik zou het niet doen', back: "I wouldn't do it" },
    { front: 'Wat zou jij doen?', back: 'What would you do?' },
    { front: 'Dat zou fijn zijn', back: 'That would be nice' },
  ],
  'b1/06-hypotheticals-with-als': [
    {
      front: 'Als ik rijk was, zou ik reizen',
      back: 'If I were rich, I would travel',
    },
    {
      front: 'Als ik tijd had, zou ik komen',
      back: 'If I had time, I would come',
    },
    { front: 'Als ik jou was, …', back: 'If I were you, …' },
    { front: 'Ik zou graag willen', back: 'I would like to' },
    { front: 'Dat zou fijn zijn', back: 'That would be nice' },
    { front: 'Stel dat …', back: 'Suppose that …' },
    { front: 'Als ik kon, zou ik helpen', back: "If I could, I'd help" },
    {
      front: 'Als het niet regende, gingen we',
      back: "If it weren't raining, we'd go",
    },
    { front: 'Wat zou je doen als …?', back: 'What would you do if …?' },
    { front: 'Als ik meer tijd had, …', back: 'If I had more time, …' },
    {
      front: 'Zonder jou zou ik het niet kunnen',
      back: "Without you I couldn't do it",
    },
    { front: 'Ik wou dat het waar was', back: 'I wish it were true' },
  ],
  'b1/07-conditional-past': [
    {
      front: 'Als ik het had geweten, zou ik zijn gekomen',
      back: 'If I had known, I would have come',
    },
    {
      front: 'Als ik eerder was begonnen, …',
      back: 'If I had started earlier, …',
    },
    {
      front: 'Ik zou het anders hebben gedaan',
      back: 'I would have done it differently',
    },
    { front: 'Dat had ik niet verwacht', back: 'I had not expected that' },
    { front: 'Als we hadden geweten …', back: 'If we had known …' },
    { front: 'Hij zou zijn gebleven', back: 'He would have stayed' },
    { front: 'Ik had het kunnen doen', back: 'I could have done it' },
    { front: 'We hadden moeten wachten', back: 'We should have waited' },
    { front: 'Als jij er was geweest, …', back: 'If you had been there, …' },
    { front: 'Ik zou nooit zijn gegaan', back: 'I would never have gone' },
    { front: 'Dat had niet gehoeven', back: "That wasn't necessary" },
    {
      front: 'Ze had het beter kunnen weten',
      back: 'She should have known better',
    },
  ],
  'b1/08-passive-with-worden': [
    {
      front: 'Het rapport wordt afgerond',
      back: 'The report is being finished',
    },
    { front: 'Er wordt hard gewerkt', back: 'People are working hard' },
    {
      front: 'De brug werd gebouwd',
      back: 'The bridge was being built (past)',
    },
    {
      front: 'Het huis wordt door hen verkocht',
      back: 'The house is being sold by them',
    },
    { front: 'De wet wordt aangenomen', back: 'The law is being passed' },
    {
      front: 'Er wordt veel gediscussieerd',
      back: 'There is a lot of discussion',
    },
    { front: 'De vergadering werd verplaatst', back: 'The meeting was moved' },
    {
      front: 'Het probleem wordt opgelost',
      back: 'The problem is being solved',
    },
    { front: 'Er werd gelachen', back: 'There was laughter' },
    {
      front: 'De uitslag wordt bekendgemaakt',
      back: 'The result is being announced',
    },
    {
      front: 'De kamer wordt schoongemaakt',
      back: 'The room is being cleaned',
    },
    {
      front: 'Het pakket wordt bezorgd',
      back: 'The package is being delivered',
    },
  ],
  'b1/09-passive-with-zijn': [
    {
      front: 'Het rapport is afgerond',
      back: 'The report has been finished (state)',
    },
    { front: 'Het venster is gebroken', back: 'The window is broken' },
    { front: 'De deur is gesloten', back: 'The door is closed' },
    { front: 'Het eten is klaar', back: 'The food is ready' },
    { front: 'De beslissing is genomen', back: 'The decision has been made' },
    { front: 'Alles is geregeld', back: 'Everything is arranged' },
    { front: 'De winkel is gesloten', back: 'The shop is closed' },
    { front: 'Het huis is verkocht', back: 'The house is sold' },
    { front: 'De brief is verstuurd', back: 'The letter has been sent' },
    { front: 'Het probleem is opgelost', back: 'The problem is solved' },
    { front: 'De tafel is gedekt', back: 'The table is set' },
    { front: 'Het werk is gedaan', back: 'The work is done' },
  ],
  'b1/10-indirect-speech': [
    { front: 'Hij zei dat hij ziek was', back: 'He said he was ill' },
    { front: 'Hij zei dat hij zou komen', back: 'He said he would come' },
    { front: 'Ze vroeg of ik tijd had', back: 'She asked if I had time' },
    {
      front: 'Hij vertelde dat hij was verhuisd',
      back: 'He said he had moved',
    },
    { front: 'de volgende dag', back: 'the next day (time shift)' },
    { front: 'Hij vroeg waar ik woonde', back: 'He asked where I lived' },
    { front: 'Ze zei dat het goed ging', back: 'She said it was going well' },
    { front: 'Hij vroeg hoe laat het was', back: 'He asked what time it was' },
    { front: 'Ik zei dat ik zou bellen', back: "I said I'd call" },
    { front: 'Ze vertelde dat ze moe was', back: 'She said she was tired' },
    {
      front: 'Hij wilde weten of ik kwam',
      back: 'He wanted to know if I was coming',
    },
    { front: 'Ze zei dat ze het niet wist', back: "She said she didn't know" },
  ],
  'b1/11-te-plus-infinitive': [
    { front: 'Het is moeilijk te zeggen', back: 'It is hard to say' },
    { front: 'Ik kom om te helpen', back: 'I come to help' },
    { front: 'zonder te vragen', back: 'without asking' },
    { front: 'na te hebben gegeten', back: 'after having eaten' },
    { front: 'Ik probeer Nederlands te spreken', back: 'I try to speak Dutch' },
    { front: 'Leuk je te ontmoeten', back: 'Nice to meet you' },
    { front: 'Ik hoop je snel te zien', back: 'I hope to see you soon' },
    { front: 'Ik ben van plan te gaan', back: 'I plan to go' },
    { front: 'Het is tijd om te gaan', back: "It's time to go" },
    { front: 'Ik heb besloten te blijven', back: "I've decided to stay" },
    { front: 'door hard te werken', back: 'by working hard' },
    { front: 'Ik sta op het punt te vertrekken', back: "I'm about to leave" },
  ],
  'b1/12-word-order-masterclass': [
    { front: 'Morgen ga ik werken', back: 'Tomorrow I go to work (inversion)' },
    {
      front: '… omdat ik morgen moet werken',
      back: '… because I have to work tomorrow (verb cluster)',
    },
    { front: 'Gisteren heb ik hem gezien', back: 'Yesterday I saw him' },
    {
      front: 'Ik ga morgen met de trein naar Utrecht',
      back: 'Time – Manner – Place example',
    },
    { front: 'Daarom blijf ik thuis', back: 'That is why I stay home' },
    {
      front: 'Ik blijf thuis, want ik ben moe',
      back: 'want keeps V2 (coordinate)',
    },
    {
      front: 'Ik heb hem gisteren op straat gezien',
      back: 'I saw him on the street yesterday',
    },
    { front: 'Zij is naar huis gegaan', back: 'She has gone home' },
    { front: '… dat ik het niet weet', back: "… that I don't know" },
    { front: 'Nu moet ik echt gaan', back: 'Now I really have to go' },
    {
      front: 'Hij wil morgen langskomen',
      back: 'He wants to come by tomorrow',
    },
    { front: 'Toch ga ik', back: "I'm going anyway" },
  ],
  'b1/13-nuanced-opinions': [
    { front: 'Naar mijn mening', back: 'In my opinion' },
    { front: 'Ik ben er niet zeker van dat …', back: 'I am not sure that …' },
    { front: 'Het lijkt me dat …', back: 'It seems to me that …' },
    { front: 'Ik twijfel of …', back: 'I doubt whether …' },
    { front: 'Voor zover ik weet', back: 'As far as I know' },
    { front: 'Ik ben bang dat …', back: 'I am afraid that …' },
    { front: 'Eerlijk gezegd', back: 'Honestly' },
    { front: 'Ik heb het idee dat …', back: 'I have the feeling that …' },
    { front: 'Het hangt ervan af', back: 'It depends' },
    { front: 'Aan de ene kant', back: 'On one hand' },
    { front: 'Ik ben ervan overtuigd dat …', back: "I'm convinced that …" },
    { front: 'Wat mij betreft', back: "As far as I'm concerned" },
  ],
  'b1/14-agreeing-and-debating': [
    { front: 'Daar ben ik het mee eens', back: 'I agree with that' },
    { front: 'Ik zie dat anders', back: 'I see it differently' },
    { front: 'Enerzijds … anderzijds', back: 'On one hand … on the other' },
    { front: 'Dat is een goed punt', back: 'That is a good point' },
    { front: 'Ik begrijp je punt', back: 'I understand your point' },
    {
      front: 'Daar ben ik het niet mee eens',
      back: 'I do not agree with that',
    },
    { front: 'Dat klopt helemaal', back: "That's completely right" },
    {
      front: 'Ik snap wat je bedoelt, maar …',
      back: 'I get what you mean, but …',
    },
    { front: 'Precies!', back: 'Exactly!' },
    { front: 'Daar zit wat in', back: "There's something in that" },
    { front: 'Ik ben het deels eens', back: 'I partly agree' },
    { front: 'Laten we het erover eens zijn', back: "Let's agree on it" },
  ],
  'b1/15-reading-the-news': [
    { front: 'volgens de bron', back: 'according to the source' },
    { front: 'het bericht meldt dat …', back: 'the report states that …' },
    {
      front: 'De regering kondigde aan dat …',
      back: 'The government announced that …',
    },
    { front: 'de kop', back: 'the headline' },
    { front: 'het artikel', back: 'the article' },
    { front: 'de bron', back: 'the source' },
    { front: 'het nieuws', back: 'the news' },
    { front: 'de krant', back: 'the newspaper' },
    { front: 'volgens de politie', back: 'according to police' },
    { front: 'naar aanleiding van', back: 'in response to' },
    { front: 'de kop van het artikel', back: "the article's headline" },
    { front: 'de journalist', back: 'the journalist' },
  ],
  'b1/16-formal-letters-and-emails': [
    { front: 'Geachte heer/mevrouw', back: 'Dear Sir/Madam' },
    { front: 'Met vriendelijke groet', back: 'Kind regards' },
    {
      front: 'Hierbij informeer ik u dat …',
      back: 'I hereby inform you that …',
    },
    {
      front: 'In de bijlage vindt u …',
      back: 'In the attachment you will find …',
    },
    {
      front: 'Met deze e-mail reageer ik op …',
      back: 'With this email I respond to …',
    },
    {
      front: 'Ik hoor graag van u',
      back: 'I look forward to hearing from you',
    },
    { front: 'Beste …', back: 'Dear …' },
    { front: 'Bij voorbaat dank', back: 'Thanks in advance' },
    {
      front: 'Naar aanleiding van uw brief',
      back: 'With reference to your letter',
    },
    {
      front: 'Ik verzoek u vriendelijk om …',
      back: 'I kindly request you to …',
    },
    { front: 'Hoogachtend', back: 'Yours faithfully' },
    { front: 'de bijlage', back: 'the attachment' },
  ],
  'b1/17-work-meetings-and-applications': [
    { front: 'sollicitatiegesprek', back: 'job interview' },
    {
      front: 'Ik zou graag willen solliciteren',
      back: 'I would like to apply',
    },
    { front: 'Kunt u dat toelichten?', back: 'Can you elaborate on that?' },
    { front: 'de agenda', back: 'the agenda' },
    { front: 'de actiepunten', back: 'action points' },
    {
      front: 'Ik solliciteer op deze functie',
      back: 'I am applying for this position',
    },
    { front: 'het cv', back: 'the CV' },
    { front: 'de motivatiebrief', back: 'the cover letter' },
    { front: 'de functie', back: 'the position' },
    { front: 'het arbeidscontract', back: 'the employment contract' },
    { front: 'Wat zijn uw sterke punten?', back: 'What are your strengths?' },
    { front: 'de notulen', back: 'the minutes' },
  ],
  'b1/18-education-and-learning': [
    { front: 'inschrijven', back: 'enrol / register' },
    { front: 'het tentamen', back: 'the exam' },
    {
      front: 'Ik studeer … aan de universiteit',
      back: 'I study … at the university',
    },
    { front: 'de docent', back: 'lecturer' },
    { front: 'de student', back: 'student' },
    { front: 'Ik heb mijn examen gehaald', back: 'I passed my exam' },
    { front: 'het diploma', back: 'the diploma' },
    { front: 'het college', back: 'the lecture' },
    { front: 'de opleiding', back: 'the study programme' },
    { front: 'huiswerk maken', back: 'to do homework' },
    { front: 'het cijfer', back: 'the grade' },
    { front: 'slagen voor het examen', back: 'to pass the exam' },
  ],
  'b1/19-society-and-environment': [
    { front: 'de gemeente', back: 'municipality' },
    { front: 'duurzaamheid', back: 'sustainability' },
    { front: 'het zorgstelsel', back: 'healthcare system' },
    { front: 'de bijstand', back: 'social assistance' },
    { front: 'het milieu', back: 'the environment' },
    { front: 'de regering', back: 'the government' },
    { front: 'de belasting', back: 'the tax' },
    { front: 'de verkiezingen', back: 'the elections' },
    { front: 'klimaatverandering', back: 'climate change' },
    { front: 'afval scheiden', back: 'to separate waste' },
    { front: 'de samenleving', back: 'society' },
    { front: 'de werkloosheid', back: 'unemployment' },
  ],
  'b1/20-feelings-and-relationships': [
    { front: 'Ik voel me …', back: 'I feel …' },
    { front: 'We hebben ruzie gehad', back: 'We had an argument' },
    { front: 'Ik vertrouw je', back: 'I trust you' },
    { front: 'Het spijt me dat …', back: 'I am sorry that …' },
    { front: 'Ik ben boos', back: 'I am angry' },
    { front: 'Ik mis je', back: 'I miss you' },
    { front: 'Ik ben blij', back: "I'm happy" },
    { front: 'Ik ben teleurgesteld', back: "I'm disappointed" },
    { front: 'Ik hou van je', back: 'I love you' },
    { front: 'We zijn uit elkaar', back: "We've broken up" },
    { front: 'Ik ben trots op je', back: "I'm proud of you" },
    { front: 'Maak je geen zorgen', back: "Don't worry" },
  ],
  'b1/21-dutch-culture-and-directness': [
    { front: 'Met alle respect, maar …', back: 'With all due respect, but …' },
    { front: 'gezellig', back: 'cosy / fun together' },
    { front: 'Zullen we iets afspreken?', back: 'Shall we plan something?' },
    {
      front: 'Nee, dat kan niet',
      back: 'No, that is not possible (direct but normal)',
    },
    { front: 'Geen probleem', back: 'No problem' },
    { front: 'Doe maar', back: 'Go ahead / never mind' },
    { front: 'Eerlijk is eerlijk', back: 'Fair is fair' },
    { front: 'Zeg maar gewoon wat je denkt', back: 'Just say what you think' },
    { front: 'Doe normaal', back: 'Act normal / behave' },
    { front: 'Even serieus', back: 'Seriously though' },
    {
      front: "Dat vind ik niet zo'n goed idee",
      back: "I don't think that's a good idea",
    },
    { front: 'Laten we afspreken', back: "Let's arrange to meet" },
  ],
  'b1/22-storytelling-past-tenses': [
    {
      front: 'Ik was net thuisgekomen toen …',
      back: 'I had just come home when …',
    },
    {
      front: 'Ik woonde in Amsterdam',
      back: 'I lived in Amsterdam (background)',
    },
    { front: 'Toen ben ik verhuisd', back: 'Then I moved (event)' },
    { front: 'Op een dag …', back: 'One day … (story opener)' },
    { front: 'Het was een drukke week', back: 'It was a busy week' },
    { front: 'Uiteindelijk …', back: 'In the end …' },
    { front: 'Eerst … toen … daarna …', back: 'First … then … after that …' },
    { front: 'Plotseling …', back: 'Suddenly …' },
    { front: 'Terwijl ik liep, …', back: 'While I was walking, …' },
    { front: 'Het begon allemaal toen …', back: 'It all began when …' },
    { front: 'Nadat we waren aangekomen, …', back: 'After we had arrived, …' },
    { front: 'Aan het eind …', back: 'In the end …' },
  ],
  'b1/23-diminutives': [
    { front: 'het kopje', back: 'the cup / cup of (coffee)' },
    { front: 'broodje', back: 'sandwich' },
    { front: 'even gezellig', back: 'a bit cosy (friendly tone)' },
    { front: 'het huisje', back: 'the little house' },
    { front: 'meisje', back: 'girl / little girl' },
    { front: 'autootje', back: 'little car (affectionate)' },
    { front: 'het biertje', back: 'the (small) beer' },
    { front: 'een kwartiertje', back: 'a quarter of an hour' },
    { front: 'het katje', back: 'the kitten' },
    { front: 'een dagje uit', back: 'a day out' },
    { front: 'het pilsje', back: 'the beer' },
    { front: 'even een momentje', back: 'just a moment' },
  ],
  'b1/24-particles-masterclass': [
    { front: 'Kom maar binnen', back: 'Come on in (welcoming)' },
    { front: 'Doe maar', back: 'Go ahead / never mind' },
    { front: 'Dat is toch logisch?', back: 'That is logical, right?' },
    { front: 'Kom gerust even langs', back: 'Feel free to drop by for a bit' },
    { front: 'Wacht even', back: 'Wait a moment' },
    { front: 'Dat is maar goed ook', back: 'That is just as well' },
    { front: 'Het is nu eenmaal zo', back: "That's just how it is" },
    { front: 'Ga toch zitten', back: 'Do sit down' },
    { front: 'Even kijken', back: "Let's see" },
    { front: 'Zeg maar', back: 'Just tell me' },
    { front: 'Het valt wel mee, hoor', back: "It's not so bad, really" },
    { front: 'Kom nou!', back: 'Come on!' },
  ],
  'b1/25-idioms-and-expressions': [
    { front: 'Het regent pijpenstelen', back: 'It is raining cats and dogs' },
    { front: 'Op de bonnefooi', back: 'On the spur of the moment' },
    { front: 'De kogel is door de kerk', back: 'The decision is made' },
    { front: 'Iets uit de losse pols', back: 'Something off the cuff' },
    { front: 'Dat valt wel mee', back: 'That is not so bad' },
    { front: 'Het komt goed', back: 'It will be fine' },
    {
      front: 'met de deur in huis vallen',
      back: 'to get straight to the point',
    },
    { front: 'de kat uit de boom kijken', back: 'to wait and see' },
    { front: 'de knoop doorhakken', back: 'to make a decision' },
    { front: 'iets onder de knie hebben', back: 'to have mastered something' },
    { front: 'nu even niet', back: 'not right now' },
    { front: 'helaas pindakaas', back: 'too bad (informal)' },
  ],
  'b1/26-fast-speech-strategies': [
    { front: 'Kunt u dat herhalen?', back: 'Can you repeat that?' },
    { front: 'Kunt u langzamer praten?', back: 'Can you speak more slowly?' },
    {
      front: 'Ik begrijp het woord … niet',
      back: 'I do not understand the word …',
    },
    { front: 'Wat bedoelt u?', back: 'What do you mean?' },
    {
      front: 'Even langzaam, alsjeblieft',
      back: 'Slowly for a moment, please',
    },
    { front: 'Kunt u dat uitleggen?', back: 'Can you explain that?' },
    { front: 'Sorry, ik verstond u niet', back: "Sorry, I didn't catch that" },
    { front: 'Wat zei u precies?', back: 'What did you say exactly?' },
    { front: 'Bedoelt u …?', back: 'Do you mean …?' },
    { front: 'Kunt u het anders zeggen?', back: 'Can you say it differently?' },
    { front: 'Nog een keer, graag', back: 'Once more, please' },
    { front: 'Ik ben even de draad kwijt', back: "I've lost the thread" },
  ],
  'b1/27-practical-netherlands': [
    { front: 'inschrijven bij de gemeente', back: 'register at municipality' },
    { front: 'het BSN', back: 'citizen service number' },
    { front: 'de zorgverzekering', back: 'health insurance' },
    { front: 'DigiD', back: 'government login' },
    { front: 'de huisarts', back: 'GP / family doctor' },
    {
      front: 'Kunt u me helpen met inschrijven?',
      back: 'Can you help me register?',
    },
    { front: 'de belastingdienst', back: 'the tax office' },
    { front: 'de verblijfsvergunning', back: 'the residence permit' },
    {
      front: 'een afspraak bij de gemeente',
      back: 'an appointment at the town hall',
    },
    { front: 'het paspoort', back: 'the passport' },
    { front: 'de bankrekening', back: 'the bank account' },
    { front: 'de toeslag', back: 'the allowance / benefit' },
  ],
  'b1/28-bringing-it-together': [
    {
      front: 'Kunt u dat herhalen?',
      back: 'Can you repeat that? (recovery phrase)',
    },
    {
      front: 'Met vriendelijke groet',
      back: 'Kind regards (formal email close)',
    },
    { front: 'Ik zou graag …', back: 'I would like … (polite request)' },
    { front: 'Naar mijn mening', back: 'In my opinion' },
    {
      front: 'Het rapport is afgerond',
      back: 'The report is finished (passive state)',
    },
    { front: 'Geachte heer/mevrouw', back: 'Dear Sir/Madam (formal open)' },
    { front: 'Zullen we afspreken?', back: 'Shall we meet up?' },
    { front: 'Ik ben het ermee eens', back: 'I agree with it' },
    { front: 'Als ik tijd had, zou ik gaan', back: "If I had time, I'd go" },
    { front: 'Het wordt geregeld', back: "It's being arranged" },
    { front: 'Hoewel het moeilijk is, …', back: "Although it's difficult, …" },
    {
      front: 'Tot slot wil ik zeggen dat …',
      back: "Finally I'd like to say that …",
    },
  ],
};

export function getLessonFlashcards(lessonId: string): FlashcardItem[] {
  return LESSON_FLASHCARDS[lessonId] ?? [];
}
